### ISSUE TITLE
Command not found!

### ISSUE THREAD

**Issue by R0b1ns** [corpnewt/gibMacOS#10]
run: {'args': ['diskpart', '/s', 'c:\\users\\user\\appdata\\local\\temp\\tmppuy4yn\\diskpart.txt'], 'stream': True}

-> ('', 'Command not found!', 1)

If i execute cmd.exe and type in, all will be fine.
diskpart /s c:\\users\\user\\appdata\\local\\temp\\tmppuy4yn\\diskpart.txt
(I commented out 331: shutil.rmtree(temp), and the file is there)

--
Same problem at line 614

**Comment by corpnewt** [comment]
Honestly, I'm not sure why it's not reading the diskpart script.  I've tested on a number of machines, and I've never run into that before.  It may be a permissions issue?  It doesn't appear to be an issue with the python script at first glance though, so I'll close this for the time being.  If others report the same, I'll reopen this issue.

-CorpNewt
