### ISSUE TITLE
Scripts/downloader.py CHUNK size should be larger

### ISSUE THREAD

**Issue by bentaylornz** [corpnewt/gibMacOS#102]
Hi,

while downloading, i noticed how frequently the progress bar was updating and how slow the download was going.. quick look found 

        CHUNK = 16 * 1024

which to me is way too low. changing this to 1024*1024 took my download speed from ~4MB/sec to my 20MB/sec limit as expected. 

just fyi :-)

**Comment by corpnewt** [comment]
Updated - thanks!

-CorpNewt
