### ISSUE TITLE
Selecting opencore with the O key gives "Disk is not an option"

### ISSUE THREAD

**Issue by ScribbleNerd** [corpnewt/gibMacOS#111]
When selecting OpenCore in the MakeInstall.bat with the O key, it shows me this:
![image](https://user-images.githubusercontent.com/31575858/83222241-710d5e80-a13d-11ea-9dfd-ef52657900ef.png)
I'm running it as admin and everything...
I'm on Windows 10 Pro 10.0.18363 Build 18363

**Comment by corpnewt** [comment]
Are you only pressing the "O" key and then enter?

-CorpNewt
