### ISSUE TITLE
makeInstall ignores installESDDmg.pkg on Win10?

### ISSUE THREAD

**Issue by sj64** [corpnewt/gibMacOS#119]
All scripts complete successfully, but on a 32GB usb drive makeinstall.bat/py only creates a 2GB BaseInstall partition (and the tiny EFI one), which also boots ok, but then demands internet and re-downloads the whole 8GB plus again, which as I am only have a mobile data connection, is prone to breaking, usually around 80%, several hours and yet more gigs of my plan gone to waste! The macos installer doesn't believe in resuming downloads, one fail and it's start from scratch again. ;o(

Yet in the the download folder created by gibMacOS.bat there is a massive 6GB installESDDmg.pkg, which I understand is used in the mac version of this script, but seems to be ignored in the win version? It certainly doesn't use it AFAICT. Is it supposed to? Or is there a way to specify that it gets used? I tried changing the self.suffixes array in makeinstall.py to use it instead of the recoveryHDmeta pkg but it fails while extracting recovery - error code 2.

This is such a great script, and apologies if I've missed something obvious...

**Comment by corpnewt** [comment]
Creating a full installer requires read/write HFS+ access, which Windows does not have by default.  MakeInstall can *only* create an internet installer for this reason - which requires the packages be downloaded in the install env.  You can toggle recovery only at the main menu with the `R` option - and when enabled, gibMacOS will only download the recovery package and omit the rest.

The reason that you *can* download all the install files for a complete install is that gibMacOS is cross-platform, and can be used anywhere python runs.  When running on macOS, you can use `BuildmacOSInstallApp.command` to create the full install app from the downloaded files as you've surmised.

-CorpNewt
