### ISSUE TITLE
Bootice link is dead in script

### ISSUE THREAD

**Issue by Polisas** [corpnewt/gibMacOS#12]
Hey,

Bootice link in python script is dead. That causes script to exit. Alternative is to include bootice manually in scripts folder or update download link from somewhere else.

**Comment by corpnewt** [comment]
I added BOOTICE to the project in the script dir - and updated the url in the script in [this commit](https://github.com/corpnewt/gibMacOS/commit/2f29333c65de3ee2432473388f5d9a2555e1e326).  It should work as intended now.

-CorpNewt
