### ISSUE TITLE
macOS Big Sur, Need new scripts to make app installer ?

### ISSUE THREAD

**Issue by sulthonuladib** [corpnewt/gibMacOS#122]
![Screen Shot 2020-06-23 at 15 30 35](https://user-images.githubusercontent.com/57745493/85379938-8623b480-b566-11ea-85a4-3dbb3ac141f7.png)

**Comment by ludufre** [comment]
Run the script, then change `Max-OS Version` (type M) to 10.16 and then change `Catalog` (type C) to developer

**Comment by drewwalton19216801** [comment]
> Run the script, then change `Max-OS Version` (type M) to 10.16 and then change `Catalog` (type C) to developer

I did this, but got the same results. The only files that get downloaded are BuildManifest.plist, Info.plist, InstallAssistant.pkg, InstallInfo.plist, MajorOSInfo.pkg, and UpdateBrain.zip.

The required file(s) for MakeInstall.{bat,py} are not downloaded.

**Comment by SavageAUS** [comment]
Using 10.16 does not show the big sur installer because isnt big sur 11.0. And the script does not accept 11.xx

**Comment by corpnewt** [comment]
10.16 is Big Sur - MakeInstall does not currently support it as the files therein have changed.

-CorpNewt

**Comment by pixelomer** [comment]
It looks like simply installing the InstallAssistant.pkg package will put the "Install macOS Beta" application into your /Applications folder, so the script is not needed.
