### ISSUE TITLE
install drive compatibility 

### ISSUE THREAD

**Issue by CreeT6** [corpnewt/gibMacOS#123]
Makeinstall won't show any external harddrives, ssd, nvme, m.2, sata drives. it only shows usb drives like sd card reader or normal flash drives. Why? is this an intentional feature? i don't want to use slow usb 2.0 flash drives when i can use highspeed ssd as external storage.

**Comment by corpnewt** [comment]
This is by design to prevent users from erasing media unintentionally.  There's an option in the main menu to show all disks:
```
D = Used without a drive number, toggles showing all disks
```

-CorpNewt
