### ISSUE TITLE
Script exiting with error code 9009

### ISSUE THREAD

**Issue by KaboomB52** [corpnewt/gibMacOS#126]
I just downloaded gibMacOS and whenever I run the gibMacOS.bat file it keeps saying "Script exited with error code: 9009"

**Comment by corpnewt** [comment]
Can you run [this script](https://gist.github.com/corpnewt/db8da712ea58ac55d46aacd75cacdf99) which collects some debugging info about your pathing/python setup - and then show me the output?

-CorpNewt

**Comment by tarektm** [comment]
Hi,
I got the same result, the TestPy.bat exited without showing the output.
Python 3.8.3
Windows 10 Pro.

**Comment by tarektm** [comment]
Solved by downgrading to 3.7.6 and manually selected the options and allowing environmental variable to be shared.

**Comment by corpnewt** [comment]
If TestPy.bat fails to open - you could open a cmd.exe window, `cd` into the directory where TestPy.bat exists, then run `TestPy.bat` and see what it reports for errors.  You shouldn't need to downgrade python - but I wonder if Windows recently changed something that's affecting things (again).

-CorpNewt

**Comment by Foodstep** [comment]
I had same problem,
I ran TestPy.bat and the result was "< was unexpected at this time."

Python 3.7.4

**Comment by corpnewt** [comment]
Hmm - that's odd - the only times the `<` character shows up is in the function definitions - where it's a valid character.

Just to be sure - can you upload the TestPy.bat file you're using and send a link?

-CorpNewt

**Comment by Foodstep** [comment]
[TestPy.txt](https://github.com/corpnewt/gibMacOS/files/4887539/TestPy.txt)

**Comment by corpnewt** [comment]
So - I'm reasonably confused.  I tested the same contents here, and it worked fine.  Opening the copy you sent results in the same error you get, but comparing the two files shows no differences.  I even went so far as to read both your (test.bat) and my (tp.bat) copies into variables in python, then compare them one character at a time ensuring equality, then write yours to a new file (t.bat) to test: 
```py
>>> with open("test.bat","r") as f:
...     t1 = f.read()
...
>>> with open("tp.bat","r") as f:
...     t2 = f.read()
...
>>> len(t1)
5628
>>> len(t2)
5628
>>> for x in range(len(t1)):
...     if not t1[x] == t2[x]:
...         print("Differ at {}".format(x))
...         print("{} != {}".format(t1[x],t2[x]))
...
>>> with open("t.bat","w") as f:
...     f.write(t1)
...
5628
```
Double-clicking t.bat works as intended.  This is on Python 3.8.2 on Windows 10 Professional build 1909.

-CorpNewt

**Comment by corpnewt** [comment]
I just updated TestPy.bat's gist again replacing any `:functionname <variable> <variable>` syntax with `:functionname    - variable variable` syntax.  Can you confirm this works?

-CorpNewt

**Comment by Foodstep** [comment]
Iterating python list
Checking python version at "C:\Users\fabio\AppData\Local\Microsoft\WindowsApps\python.exe"
- Checking for version number: "was"
Checking python version at "C:\Users\fabio\AppData\Local\Microsoft\WindowsApps\python3.exe"
- Checking for version number: "was"
Checking python version at "C:\Windows\py.exe"
- Checking for version number: "3.7.4"
- Got version number
- Validating version was captured
- Got valid version: "3.7.4"
- Python 3
- Version is higher than current - saving

Python 2 path found:  ""
Python 2 version:     ""
Python 3 path found:  "C:\Windows\py.exe"
Python 3 version:     "3.7.4"

**Comment by corpnewt** [comment]
I just updated the `gibMacOS.bat` file in [this commit](https://github.com/corpnewt/gibMacOS/commit/336d294af70cda4d0cebf53d8a8141656760f0ed) with the same general changes. If that works, I'll push the changes to the rest of my .bat starters.  Please let me know if that fixed it (note:  MakeInstall.bat is unchanged at this time - so only gibMacOS.bat will have the fixes).

-CorpNewt

**Comment by Foodstep** [comment]
![image](https://user-images.githubusercontent.com/30118538/86856750-d2481c00-c071-11ea-8ae9-a701234fcdc3.png)

**Comment by corpnewt** [comment]
Hmm - can you send the gibMacOS.bat file you have?  I'll test here as well and see if I can figure out what's going on.

-CorpNewt

**Comment by Foodstep** [comment]
Sorry, I ran the wrong file, I ran the correct one and we have a lot of "errors"

C:\Users\fabio\Desktop\Hack\aaaaaa>Search or jump toΓÇª
'Search' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\fabio\Desktop\Hack\aaaaaa>Pull requests
'Pull' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\fabio\Desktop\Hack\aaaaaa>Issues
'Issues' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\fabio\Desktop\Hack\aaaaaa>Marketplace
'Marketplace' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\fabio\Desktop\Hack\aaaaaa>Explore
'Explore' is not recognized as an internal or external command,
operable program or batch file.
'Foodstep' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\fabio\Desktop\Hack\aaaaaa>Learn Git and GitHub without any code!
'Learn' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\fabio\Desktop\Hack\aaaaaa>Using the Hello World guide, youΓÇÖll start a branch, write comments, and open a pull request.
'Using' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\fabio\Desktop\Hack\aaaaaa>corpnewt
'corpnewt' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\fabio\Desktop\Hack\aaaaaa>/
'/' is not recognized as an internal or external command,
operable program or batch file.

**Comment by corpnewt** [comment]
Uhh - that's just the header for the actual github page for gibMacOS but "parsed" in the cmd prompt (?):

![image](https://user-images.githubusercontent.com/12772521/86857131-75556180-c083-11ea-98ad-e9dfc6d075d1.png)

Are you sure you have the proper files?  You may try downloading the latest zip from [this link](https://github.com/corpnewt/gibMacOS/archive/master.zip).

-CorpNewt

**Comment by Foodstep** [comment]
Sorry for the delay, I needed to stop trying...
I downloaded the new version of the project and ran gibMacPs.bat again and I had same result "Script exited with error code: 9009"
This was the files that I used.
[GibMacOS.zip](https://github.com/corpnewt/gibMacOS/files/4890408/GibMacOS.zip)

**Comment by dmytro-frolov** [comment]
Hi guys,

Had the same issue today, I downloaded this branch and ran instead of the latest. The script asked me if I have python installed instead of an error, so I agreed. After that latest version of gibMacOS works fine.

https://github.com/corpnewt/gibMacOS/archive/7a17c3fc117817462f615b34126af8c2e291cfca.zip

**Comment by Foodstep** [comment]
Yeah @dmytro-frolov, it's work for me too, Thank you, @corpnewt can I use this way that @dmytro-frolov showed to us?

**Comment by corpnewt** [comment]
It looks like there's an issue with my `ComSpec` env variable rebuilding.  It *seems* that adding `"tokens=* delims="` to the for loop fixes the issue and allows for the prior `:functionname <variable>` notation.  Could you check if the `gibMacOS.bat` in [this commit](https://github.com/corpnewt/gibMacOS/commit/0a1ca788d1b40500a2fca16da4c334bc4f07b599) is working?

-CorpNewt

**Comment by KaboomB52** [comment]
@corpnewt Sorry for taking so long but the testpy thing comes back with this https://ghostbin.co/paste/8z2fx

**Comment by corpnewt** [comment]
No problem - can you test the `gibMacOS.bat` in the latest commit that I just posted?  I think I may have fixed it - but batch is quite the fickle scripting language.

-CorpNewt

**Comment by Foodstep** [comment]
It seems working now :)
![image](https://user-images.githubusercontent.com/30118538/86951044-d9b90500-c105-11ea-98ae-ee3b31c1a789.png)

**Comment by corpnewt** [comment]
Wonderful - I'll go through and update the rest of the .bat starter scripts.  Thank you everyone for testing.

-CorpNewt

**Comment by KaboomB52** [comment]
It still has the error for me

**Comment by corpnewt** [comment]
@KaboomB52 Can you send a screenshot?

**Comment by KaboomB52** [comment]
It was just my version of python nvm I changed it to Foodstep's version and it worked

**Comment by corpnewt** [comment]
Sweet - glad that seems to have fixed it.

-CorpNewt

**Comment by Foodstep** [comment]
yeah it's true my python version is Python 3.8.3 now
