### ISSUE TITLE
No partitions located on disk!

### ISSUE THREAD

**Issue by axlyody** [corpnewt/gibMacOS#13]
got error "No partitions located on disk!" while installing to hdd
![image](https://user-images.githubusercontent.com/8794792/60483531-00a55580-9cc0-11e9-9c2d-f93afe136e29.png)

![image](https://user-images.githubusercontent.com/8794792/60483519-f5522a00-9cbf-11e9-972f-8cfd039757d7.png)
![image](https://user-images.githubusercontent.com/8794792/60483510-e9fefe80-9cbf-11e9-8723-29a6bb2e7375.png)

**Comment by corpnewt** [comment]
Typically denotes one of the following:

* You may be using a third party partitioning or disk management software that interferes
* The USB may be faulty
* Windows/DiskPart may be misconfigured

The code where that line is printed is as follows:
```py
        # At this point, we should have a boot0xx file and an EFI folder in the temp dir
        # We need to udpate the disk list though - to reflect the current file system on part 1
        # of our current disk
        self.d.update() # assumes our disk number stays the same
        # Some users are having issues with the "partitions" key not populating - possibly a 3rd party disk management soft?
        # Possibly a bad USB?
        # We'll see if the key exists - if not, we'll throw an error.
        if self.d.disks[str(disk["index"])].get("partitions",None) == None:
            # No partitions found.
            shutil.rmtree(temp,ignore_errors=True)
            print("No partitions located on disk!")
            print("")
            self.u.grab("Press [enter] to return...")
            return
```

You could try on another machine, or with another USB and see if that helps.

-CorpNewt
