### ISSUE TITLE
InstallAssistant.pkg will never fully install for macOS Big Sur dev beta 2.

### ISSUE THREAD

**Issue by jawshoeadan** [corpnewt/gibMacOS#133]
Whenever I try to download Big Sur beta 2, the download for InstallAssistant.pkg won’t complete and the file size will be anywhere from .5 to 2 gb depending on where the download decided to stop. Hasn’t worked on either of my computers. When I try to install the Big Sur installer that is created, I get an error because the installer is incomplete. Creating install media from this broken installer doesn’t work either.

**Comment by chromer030** [comment]
The size for InstallAssistant.pkg of Big Sur beta 2 is around 9 GB !
gibMacOS has some issues in downloading.
Get the link of file (present as option on gibMacOS)  and download it via a Download Manager like aria2c which has also resume support.

**Comment by Baves** [comment]
It's the same for every file over 30MB. I tried to download different versions of MACOS in the gibmacos program, but the download just skips the file that can't be downloaded. Tried to download them via the links in chrome, but it downloads only with barely 1 Mbit/s (I have 300 Mbit/s) and the download stops every minute saying "Error - Networkerror".

**Comment by gabrielecappellaro** [comment]
I'm also trying to download it via the link but with Chrome it immediately says "Download failed. Network error" and with Safari I can download only 8mb then it stops.

**Comment by cheesycod** [comment]
I think thats your wifi, I cant reproduce this

**Comment by jawshoeadan** [comment]
It seems it was an issue with apples servers at the time
