### ISSUE TITLE
Download stopping on High Sierra

### ISSUE THREAD

**Issue by h1p3rcub3** [corpnewt/gibMacOS#134]
Hi,

I'm trying to download High Sierra, but all the file downloads get interrupted after a brief time. It ends the process without errors, but the size of all the download folder is about 400mb. Is this a problem with gibMacOS or with Apple servers?

**Comment by Baves** [comment]
Try it now! I had the exact same problem last night and this morning, but it seems fixed (just downloaded Catalina). I think the servers of apple were down idk.

**Comment by h1p3rcub3** [comment]
Yes. It was weird. High Sierra failed, but other versions worked fine. They all work fine now.
