### ISSUE TITLE
MakeInstall.bat error

### ISSUE THREAD

**Issue by pashenmebaojinwo** [corpnewt/gibMacOS#136]
![IMAG1](https://user-images.githubusercontent.com/43331024/88085724-d3706180-cbb8-11ea-9f6e-973b449f3c8a.PNG)
![IMAGE2](https://user-images.githubusercontent.com/43331024/88085729-d53a2500-cbb8-11ea-927d-a95771c2be4b.PNG)

**Comment by pashenmebaojinwo** [comment]
win10用户为中文会报错，改为英文用户名即可

**Comment by sckocn** [comment]
这个makeinstall只支持win10，不支持win7 64bit
