### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\qqwbzl\\AppData\\Local\\Temp\\tmpjqml32xa\\boot'

### ISSUE THREAD

**Issue by pashenmebaojinwo** [corpnewt/gibMacOS#138]
![image](https://user-images.githubusercontent.com/43331024/88425172-8e9b3380-ce21-11ea-89d7-2d84e25d771b.png)
Hlep ME! MakeInstall.py URL erro!

**Comment by aksdad** [comment]
There was a change made to https://github.com/acidanthera/OpenCorePkg/tree/master/Utilities/LegacyBoot, might wanna try using an older version of the repo. I haven't done this myself yet, I'll report back if it works.

**Comment by aksdad** [comment]
I changed this line in MakeInstall.py to `self.oc_boot_url = "https://github.com/acidanthera/OpenCorePkg/raw/4982d8c5526362d0ae5f3bca5cec25bc588e8515/Utilities/LegacyBoot/"` and it lets me create the installer. Haven't actually installed yet so proceed with caution.

**Comment by zdj0925** [comment]
我昨天也遇到同样的问题，尝试将你的C:/ 清理一下，有6G以上的空间。
