### ISSUE TITLE
Big Sur-Create install Media

### ISSUE THREAD

**Issue by Emanuele-1998** [corpnewt/gibMacOS#139]
to create the .app i run installassistant.pkg but from terminal command it gives me invalid app.![image](https://user-images.githubusercontent.com/67318166/88455949-0dbc5600-ce7a-11ea-87d8-012779d58a7a.png)

**Comment by fareszr** [comment]
use installassistant

#122

**Comment by fareszr** [comment]
#122

**Comment by hasrt1206** [comment]
How do you download BigSur via gibmacos?
I have tried but latest build is Catalina

**Comment by gspannu** [comment]
> to create the .app i run installassistant.pkg but from terminal command it gives me invalid app.!

I had the same issue and this is how it got resolved. **The steps are important.**

1) Run gibMacOS.command
2) Press M, change version to 10.16
3) Press C, change to developer (option 4)
4) Now choose 1 (This will download the RC, or version 20B5022a)

Now download.... then run InstallAssistant.pkg.
Then run createinstallmedia - and everything runs fine.

_If you do not change the version to 10.16 (**Step 2**), you can still download the BigSur beta... but you then get the SharedSupport.dmg error. This is what I figured out in my trial & error._

I also checked the InstallAssistant.pkg using 'Suspicious Package' and the version downloaded without 10.16 (Step 2) shows a verification error on SharedSupport.dmg file.
However, the downloaded pkg file using step 2 does not show a verification error 👍 

The above worked for me - give it a try if it works for you !
