### ISSUE TITLE
Linux support ?

### ISSUE THREAD

**Issue by nikos9742** [corpnewt/gibMacOS#14]
Hi, 
Just to be sure before I start changing things. What does it take to make "MakeInstall.py" run on Linux?
Best regards

**Comment by corpnewt** [comment]
You'd be looking at mostly rewriting the whole tool.  Much of it is very Windows specific (the disk query and format approaches, 3rd party tools, etc).  Midi has a guide on doing it for Linux manually [here](https://internet-install.gitbook.io/macos-internet-install/preparing-your-installer.../preparing-your-installer-media...#loonix-linux), which might be worth looking into if you plan to automate it.

I currently have no plans to add that though.  I'll close the issue - but feel free to keep responding as I'll get notified of each response and check them.

-CorpNewt

**Comment by RossComputerGuy** [comment]
@corpnewt That link is kinda broken, I get a security warning.

**Comment by Masamune3210** [comment]
Link works fine, your security software is on crack

**Comment by RossComputerGuy** [comment]
Fixed it, NextDNS decided to block GitBook.
