### ISSUE TITLE
Can't read drives made using MakeInstall.bat

### ISSUE THREAD

**Issue by shivangswain** [corpnewt/gibMacOS#142]
I have tried two separate drives (USB 2.0 & 3.0) and no matter what I do, I am not able to open the drives after they are made using MakeInstall.bat. Also to be clear, I was facing this issue before and after the latest double commit. (https://github.com/corpnewt/gibMacOS/commit/6415ddf48d0d179efb510a3e10eb53443afee086 & https://github.com/corpnewt/gibMacOS/commit/3c4f1d2b8d8c943cfdcedf662d6603aca0f0d321)

![image](https://user-images.githubusercontent.com/33395916/88467237-94ad1500-cef2-11ea-8105-3a917d408b0d.png)

![image](https://user-images.githubusercontent.com/33395916/88467250-b8705b00-cef2-11ea-93c2-532093910247.png)

![image](https://user-images.githubusercontent.com/33395916/88467287-33397600-cef3-11ea-837b-50338cd62d4f.png)

**Comment by corpnewt** [comment]
Can you check if it's working as of [this commit](https://github.com/corpnewt/gibMacOS/commit/07ef24dc36411e2f83a51778ba08600207781999)?

-CorpNewt
