### ISSUE TITLE
Error with MakeInstall.bat can't find boot file in appdata\\local\\temp

### ISSUE THREAD

**Issue by richardphan01** [corpnewt/gibMacOS#143]
![error](https://user-images.githubusercontent.com/55608314/88467994-8687d600-ceab-11ea-975e-e107e7fc3e93.png)

**Comment by zdj0925** [comment]
清理一下C:\盘 应该是C盘的存储空间不够了

**Comment by shivangswain** [comment]
Another solution would be to download the latest commits of gibMacOS

**Comment by richardphan01** [comment]
Thanks for some reason I deleted everything, redownloaded gibMacOs then redid the process and it worked
