### ISSUE TITLE
Downloading from zero

### ISSUE THREAD

**Issue by darkforce95** [corpnewt/gibMacOS#15]
hi . from the title, I have a potato internet that is so slow. it was like 300kbps.. while using your tool, somehow it did stuck on 54.2% on download 5GB worth of data. after the program did not respond, download progress never increases, I did try to restart the program. after that it trying to download from zero and not continuing the download progress. is there any implementation to continuing the downloading progress?

**Comment by corpnewt** [comment]
I don't currently have any plans to add download resume to the script - I could look into it at some point if I have time, but it's not in the current development pipeline.

-CorpNewt

**Comment by Leebgit** [comment]
It would be great if you could add this as some Internet connections are very slow. Just spent 4 hours downloading and then the connection broke and I had to start again.
