### ISSUE TITLE
macOS Big Sur is not 10.16

### ISSUE THREAD

**Issue by ultratiem** [corpnewt/gibMacOS#151]
macOS Big Sur is consistently listed as being 10.16. It is not. It is 11.0.

**Comment by hasrt1206** [comment]
Did you manage to download BigSur?
I am not able. Cannot see it ion the catalog.

**Comment by ultratiem** [comment]
@hasrt1206 and @luigi370 both of you are **_grossly_** off topic. I'm closing this report.
