### ISSUE TITLE
gibMacOS.bat doesn't do anything

### ISSUE THREAD

**Issue by NicholasMcMillan03** [corpnewt/gibMacOS#153]
whenever I run gibMacOS.bat a command prompt windows pops up and instantly goes away again. does this running as administrator or not

**Comment by yuuFen** [comment]
In the beginning it was the same for me, and then I ran it in cmd, and it prompted me to configure the environment variable incorrectly

**Comment by MeatyRocks** [comment]
I just ran it on a different computer and it worked fine so it was probably something on my end.

**Comment by Mrakonja** [comment]
@MeatyRocks  and others with similar problem - this is the long shot with one huge assumption but it might be possible that you dont have python in your paths.
