### ISSUE TITLE
Some strange with a Windows 10 1809

### ISSUE THREAD

**Issue by antrophoscode** [corpnewt/gibMacOS#16]
When i run MakeInstall - it runs with only a black screen. I need to remove permissions check on bat file to fix it. 
https://media.discordapp.net/attachments/263757191608139779/605112979129761796/unknown.png?width=909&height=469

**Comment by corpnewt** [comment]
Hmm - is it waiting for you to click "Yes" on the UAC prompt?  Does the account you're using have admin privileges?  The script auto-elevates as diskpart needs admin privs.

-CorpNewt
