### ISSUE TITLE
Big Sur beta 5 basesystem.dmg missing

### ISSUE THREAD

**Issue by lord4170** [corpnewt/gibMacOS#160]
So I used GibMacOS to download Big Sur beta 5 , and I used URL mode to download with IDM , now when I try to build .app file I get this error : 
That folder is missing the following required files:
BaseSystem.dmg, BaseSystem.chunklist, InstallESDDmg.pkg, AppleDiagnostics.dmg, AppleDiagnostics.chunklist

I have downloaded these file : BuildManifest.plist - Info.plist - InstallAssistant.pkg - InstallInfo.plist - MajorOSInfo.pkg - UpdateBrain.zip

**Comment by corpnewt** [comment]
If you run `InstallAssistant.pkg` it will place the .app in your _/Applications_ directory.  There's no need to run the `BuildmacOSInstallApp.command` for that with Big Sur.

-CorpNewt

**Comment by 0nTheGoRepairs** [comment]
I'm runing Monterey and when I run InstallAssistant it doesn't create the installer. Do I have to actually click install and type in my password?
