### ISSUE TITLE
Big Sur beta no latest release. 

### ISSUE THREAD

**Issue by lcyf9102s** [corpnewt/gibMacOS#169]
![Screen Shot 2020-09-25 at 8 35 10 AM](https://user-images.githubusercontent.com/56214862/94213712-2e506d00-ff0a-11ea-96f5-1a4bd39a7610.png)
beta 8(5374i) has been out for 2 days, but it only got beta 6(5364e).

**Comment by corpnewt** [comment]
Apple hasn't put it in the sucatalog.  The latest available is beta 6.  This is not the fault of, or a problem with gibMacOS.

-CorpNewt
