### ISSUE TITLE
Extraction error while trying to restore image

### ISSUE THREAD

**Issue by fedrenfg** [corpnewt/gibMacOS#17]
I am getting extraction error 2 while restoring image to drive.?
How can i solve this?
Just to test i tried to manually extract that .pkg file and in that case also 7zip gave extraction error.
I tried other version and 7zip gave payload error.
Please Help !!!!
![Annotation 2019-07-29 135806](https://user-images.githubusercontent.com/53425082/62033331-5874a500-b209-11e9-9456-29ed3cecf1b2.png)

**Comment by corpnewt** [comment]
Sounds like the package didn't download correctly.  You could try redownloading it - or picking another version to download.

-CorpNewt
