### ISSUE TITLE
Possible error now with OpenCore 0.6.2

### ISSUE THREAD

**Issue by MatiasLGonzalez** [corpnewt/gibMacOS#173]
I was starting to make my bootable usb following the OpenCore guide, then I noticed the guide suddenly started referencing OpenCore 0.6.2, so I checked the OC github and found OC was just updated one hour ago, so decided to start over, so I ran MakeInstall.bat and with the "O" argument and now it's giving me this error at the step of installing OC

```
Gathering info...
 - Got OpenCore-0.6.2-RELEASE.zip
Downloading...
Downloaded 4.03 MB of 4.03 MB (100.00%)
Extracting OpenCore-0.6.2-RELEASE.zip...
Gathering DUET boot files...
 - boot
 - boot0
 - boot1f32
Copying EFI folder to F:/EFI...
Traceback (most recent call last):
  File "C:\Users\Matías\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 879, in <module>
    w.main()
  File "C:\Users\Matías\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 875, in main
    self.main()
  File "C:\Users\Matías\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 801, in main
    self.main()
  File "C:\Users\Matías\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 874, in main
    self.diskpart_erase(selected_disk, use_gpt, clover_version)
  File "C:\Users\Matías\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 310, in diskpart_erase
    self.select_package(disk, clover_version)
  File "C:\Users\Matías\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 406, in select_package
    self.dd_image(disk, os.path.join(temp, hfs), clover_version)
  File "C:\Users\Matías\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 444, in dd_image
    if clover_version == "OpenCore": self.install_oc(disk)
  File "C:\Users\Matías\Downloads\gibMacOS-master\gibMacOS-master\MakeInstall.py", line 513, in install_oc
    shutil.copytree(os.path.join(temp,"EFI"), "{}/EFI".format(part))
  File "C:\Users\Matías\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'C:\\Users\\MATAS~1\\AppData\\Local\\Temp\\tmpnxifrywo\\EFI'

Script exited with error code: 1
```

"The system cannot find the path specified"

As I said before, it was working just a few hours ago when 0.6.1 was the latest release

**Comment by corpnewt** [comment]
Should be fixed in the latest commit.

-CorpNewt

**Comment by MatiasLGonzalez** [comment]
Might be related or not but now I'm getting this error

```
  #######################################################
 #                Installing OpenCore                  #
#######################################################

Gathering info...
 - Got OpenCore-0.6.2-RELEASE.zip
Downloading...
Downloaded 4.03 MB of 4.03 MB (100.00%)
Extracting OpenCore-0.6.2-RELEASE.zip...
Gathering DUET boot files...
 - boot
 - boot0
 - boot1f32
Lost original disk - or formatting failed!

Press [enter] to return...
```

And the 200MB ends up without a file system and the second one as RAW

**Comment by d-birkhead** [comment]
Same issue as above. Fails on installing open core. "Lost original disk".

Not sure why this is happening? Any quick fixes?

**Comment by MatiasLGonzalez** [comment]
I basically just kept on trying, I also did many quick and one "slow" format to the drive, it eventually worked but sorry that's all I got (still I haven't tested booting from the usb so I can't tell you if it actually worked)

**Comment by d-birkhead** [comment]
What a headache! I suspect there is just a PList setting or a BIOS setting holding you back at that stage. Everything seems to be running smoothly otherwise.

The “original disk” it keeps losing seems to be the temp folder it extracts to during the OpenCore install if I’m not mistaken. I doubt I’ll figure it out but I may try modifying the python script and see if I can solve it that way.

**Comment by MatiasLGonzalez** [comment]
Indeed, most like something about my plist. Also, yes, with the latest commit and opencore update the efi folder for each architecture was move to different folders, so it needed an updated path, which was done in the latest commit, so really I can't think of a possible cause for the issue we were having, even worse I've done the whole process again a couple of times without encountering that issue again, and with no changes in the software of any kind, so I don't have anything else to tell you besides keep trying :/

**Comment by d-birkhead** [comment]
I decided to try an external USB NVME drive and it worked flawlessly. I think the installer is fussy about drives for some reason.

Anyone encountering this should simply try a different USB drive.
