### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by Atalantia** [corpnewt/gibMacOS#177]
I recognized that the download fails very easy. I had to start the download 3 to 4 times until it runs trough. It starts over every time even there is only one small file missing. A resume function would be appreciated.

**Comment by AnwarShah** [comment]
+1 for this

**Comment by corpnewt** [comment]
There is an option to print the URLs instead of having gibMacOS download them for you - this allows you to download them with whatever other downloader you choose.  I have no explicit plans to add resume currently as alternative downloaders are likely still a better solution.

-CorpNewt
