### ISSUE TITLE
No drives showing on Win10 1903

### ISSUE THREAD

**Issue by J-Teijeiro** [corpnewt/gibMacOS#18]
I tried with a 10 different drives, running it as an admin and even changing the python script from detecting only 0 and 2 drives to 0,1,2,3,4,5,6. But it still doesn't show any drive.
When running 
```wmic logicaldisk get deviceid,filesystem,volumename,size,drivetype```
It shows my usb drives as type 2, so i don't know if wmic is lying or if there's something broken for build 1903
![2019 08 23-01 34](https://user-images.githubusercontent.com/44932886/63557187-ff6a0980-c547-11e9-863f-3e954f8ac94b.png)

**Comment by corpnewt** [comment]
You can try uncommenting [this line](https://github.com/corpnewt/gibMacOS/blob/master/MakeInstall.py#L655) to show all available disks and see if that works.  The final line would go from:
```py
        # rem_disks = self.d.disks
```
to:
```py
        rem_disks = self.d.disks
```

If `wmic` already reports them as type 2 though, they _should_ be detected by the script, as it searches for types 0 and 2 via [the following](https://github.com/corpnewt/gibMacOS/blob/master/MakeInstall.py#L97-L102):
```py
    def get_disks_of_type(self, disk_list, disk_type=(0,2)):
        disks = {}
        for disk in disk_list:
            if disk_list[disk].get("type",0) in disk_type:
                disks[disk] = disk_list[disk]
        return disks
```

But it is worth noting that there's 3 commands diskwin.py runs to map disk information:
```
wmic diskdrive get deviceid,model,index,size,partitions /format:csv
wmic path Win32_LogicalDiskToPartition get antecedent,dependent
wmic logicaldisk get deviceid,filesystem,volumename,size,drivetype /format:csv
```
It might be worth cross referencing that info to ensure everything is reporting correctly.

-CorpNewt

**Comment by J-Teijeiro** [comment]
Nope, nothing changes when uncommenting that line. I attach an screenshot with the 3 commands, but for me it seems everything okay.
![2019 08 23-03 54](https://user-images.githubusercontent.com/44932886/63561331-dbafbf00-c559-11e9-988c-adb95b567b7a.png)

**Comment by corpnewt** [comment]
Can you get me the output of those three `wmic` commands exactly as I typed them?  I'll see if I can figure out where things are dropping off.

-CorpNewt

**Comment by J-Teijeiro** [comment]
If i have don't remove the /format:csv at the end it gives me an error, i'll change my language settings to english and when it finishes i'll screencap the full command outputs

**Comment by corpnewt** [comment]
Oh - that likely explains it - as that is a part of the commands the diskwin.py module runs to gather info:
```py
disks = self.r.run({"args":[self.wmic, "diskdrive", "get", "deviceid,model,index,size,partitions", "/format:csv"]})[0]

parts = self.r.run({"args":[self.wmic, "logicaldisk", "get", "deviceid,filesystem,volumename,size,drivetype", "/format:csv"]})[0]
```
If those commands fail - then no output would be returned, and the script would effectively not see any disks.

What error does it give you when you append `/format:csv` to the end of those commands?

-CorpNewt

**Comment by J-Teijeiro** [comment]
Well, for some reason, when the windows language is english it just works perfectly. I don't have any clue on how that's remotely possible, but yeah it was just windows doing windows things

**Comment by corpnewt** [comment]
Sounds about right - I'll keep that in mind in case someone else runs into the issue.  For the time being, I'll close this issue.

-CorpNewt

**Comment by ReVG08** [comment]
I have received the same error, yet still my default system language is English
![image](https://github.com/corpnewt/gibMacOS/assets/81494730/9ba0a39e-be72-42c3-883f-96d1cfb8ee2e)

No disks are shown
