### ISSUE TITLE
Big Sur Beta 10 - BuildmacOSInstallApp failed

### ISSUE THREAD

**Issue by Matgen84** [corpnewt/gibMacOS#181]
Hi

BuildmacOSInstallApp can't build Big Sur Beta 10 Installer. **Any solutions**. Please.

 #######################################################
 #              Missing Required Files                 #
#######################################################

That folder is missing the following required files:
BaseSystem.dmg, BaseSystem.chunklist, InstallESDDmg.pkg, AppleDiagnostics.dmg, AppleDiagnostics.chunklist

**gitmacOS.command download this files:** 

 #######################################################
 #                 Downloaded 6 of 6                   #
#######################################################

Succeeded:
  MajorOSInfo.pkg
  InstallAssistant.pkg
  Info.plist
  UpdateBrain.zip
  BuildManifest.plist
  InstallInfo.plist

Failed:
  None

**Comment by gspannu** [comment]
Run InstallAssistant.pkg and this will create a 'Install macOS Big Sur Beta' app in your applications folder.

You may still face a problem when creating a bootable installer using createinstallmedia as the 'SharedSupport.dmg' file contained is not verifiable.... Still trying to work out the issue.

**Comment by bunnyonthemoon** [comment]
How can i run this file, i dont understand

**Comment by PencilNotPen** [comment]
Any news on the SharedSupport.dmg problem? I can't mount it, and it prevents createinstallmedia from making a USB drive from it too. Had this problem with the last betas too, and now with RC 2. With the previous betas I could use the developer profile to download Big Sur.app through System Preferences instead, but that doesn't work with RC 2 to gibmacOS is my only shot. Let me know if you work out why gibmacOS' downloaded SharedSupport.dmg is unusable. Thanks.

**Comment by gspannu** [comment]
> Any news on the SharedSupport.dmg problem? I can't mount it, and it prevents createinstallmedia from making a USB drive from it too. Had this problem with the last betas too, and now with RC 2. With the previous betas I could use the developer profile to download Big Sur.app through System Preferences instead, but that doesn't work with RC 2 to gibmacOS is my only shot. Let me know if you work out why gibmacOS' downloaded SharedSupport.dmg is unusable. Thanks.

Solution [here](https://github.com/corpnewt/gibMacOS/issues/139#issuecomment-723275624).

**Comment by PencilNotPen** [comment]
> > Any news on the SharedSupport.dmg problem? I can't mount it, and it prevents createinstallmedia from making a USB drive from it too. Had this problem with the last betas too, and now with RC 2. With the previous betas I could use the developer profile to download Big Sur.app through System Preferences instead, but that doesn't work with RC 2 to gibmacOS is my only shot. Let me know if you work out why gibmacOS' downloaded SharedSupport.dmg is unusable. Thanks.
> 
> Solution [here](https://github.com/corpnewt/gibMacOS/issues/139#issuecomment-723275624).

Haha, I was just coming back to say that it was now working for me, after re-downloading Big Sur, but I didn't know why. I assumed something had changed on Apple's end, but reading your link I see now that I did switch the max version in between attempts! Anyway, thanks a lot for the explanation, glad it's working now.
