### ISSUE TITLE
How to download specific Big Sur Beta? 

### ISSUE THREAD

**Issue by matisiekpl** [corpnewt/gibMacOS#182]
Hello.
How can I download specific beta version of Big Sur? (in my case Beta 9)
Thanks,
Matt W.

**Comment by hyunwoo6321** [comment]
@matisiekpl you can chose it by build number (beta 9 - 20A5384C)

**Comment by matisiekpl** [comment]
@hyunwoo6321 so instead of typing numer from 1 to n, I just type version like `20A5384C`?

**Comment by hyunwoo6321** [comment]
@matisiekpl no
for example, you have to type 3 for this case.
<img width="682" alt="스크린샷 2020-10-29 오후 10 38 03" src="https://user-images.githubusercontent.com/65493966/97581170-975e5f80-1a37-11eb-80f9-90e01364809b.png">

**Comment by matisiekpl** [comment]
@hyunwoo6321 well, but what should I do, when there is no option for specific version of beta in list? For example I want to download Big Sur beta 3, which is not on list

**Comment by hyunwoo6321** [comment]
@matisiekpl umm..... can you please follow this directions?
1. type m and enter
2.type 10.16 and enter
3. type c and enter
4. type 4 and enter

**Comment by matisiekpl** [comment]
@hyunwoo6321 
After doing these commands I'm getting following list. How can I download for example 20A5384c (I am running gibmacos on 20A5384c, maybe the problem is that there are the same versions)?
![image](https://user-images.githubusercontent.com/21008961/97585210-2c8e3380-19f9-11eb-9c8c-44d3f716c1bf.png)

**Comment by hyunwoo6321** [comment]
@matisiekpl than, can you type these in there
1. type m and enter
2. type 10.16 and enter
3. type c and enter
4. type 3 and enter

**Comment by matisiekpl** [comment]
@hyunwoo6321 
great, now I can download Beta 9. But what If I need to download for example beta 8? Or previous betas?

**Comment by hyunwoo6321** [comment]
@matisiekpl It's good to hear you are good now. But I don't know the way to download previous betas. In gibmacos, usually releases are vanished when the new version is out(I think beta 9 is a mistake)

**Comment by matisiekpl** [comment]
@hyunwoo6321 
Well, is it impossible to download previous versions of betas because of gibmacos? Or Apple removes previous versions from their servers?
Maybe should I open feature request?

**Comment by hyunwoo6321** [comment]
I think apple removes it, but it's not sure.

**Comment by MikeBeaton** [comment]
Apple removes it

**Comment by matisiekpl** [comment]
Ok, closing
