### ISSUE TITLE
GibMacOS and Big Sur

### ISSUE THREAD

**Issue by Spiderboy1949** [corpnewt/gibMacOS#191]
When I run BuildmacOSInstallApp

 #######################################################
 #              Missing Required Files                 #
#######################################################

That folder is missing the following required files:
BaseSystem.dmg, BaseSystem.chunklist, InstallESDDmg.pkg, AppleDiagnostics.dmg, AppleDiagnostics.chunklist

The Big Sur directory in macOS Downloads
<img width="601" alt="Screen Shot 2020-11-13 at 12 56 10 pm" src="https://user-images.githubusercontent.com/61126896/99023126-b02a5180-25af-11eb-88ec-b9cb386b036f.png">

Cheers Derek

**Comment by jackc88** [comment]
I encountered the same issues as you and wasn't about give up on the 12GB+ download.  I launched InstallAssistant.pkg and watched the installer log and saw the Install macOS Big Sur.app created under /Applications.  I hope that works for you as well and good luck.

**Comment by Spiderboy1949** [comment]
Also launched the pkg. Thanks

**Comment by corpnewt** [comment]
There is no Big Sur recovery package in the software update catalog - as such, MakeInstall is incompatible with it. Apple changed the way it delivers updates with Big Sur.

-CorpNewt

**Comment by hectorgrom** [comment]
Don´t install.....  :(

![Captura de Tela 2020-11-25 às 15 51 18](https://user-images.githubusercontent.com/61702551/100270127-5a05c880-2f36-11eb-9f2b-a02c95f923d0.png)

**Comment by Masamune3210** [comment]
...I mean of course it doesn't. It's not a complete installer
