### ISSUE TITLE
Unable to make an installation USB stick with macOS Big Sur on Windows due to missing recovery package

### ISSUE THREAD

**Issue by Rakleed** [corpnewt/gibMacOS#193]
I'm trying to download macOS Big Sur and make a bootable USB stick on Windows, but I get an error. That's what I'm doing:
1. Run gibMacOS.bat.
2. Enter "m" and then "10.16".
3. Enter "1" to download macOS Big Sur 11.0.1 (20B29).
4. After the download is complete, I close this app and run MakeInstall.bat as administrator.
5. Enter "D" and then "2", since I have a USB stick under that number, and then enter "y".
6. In gibMacOS folder, I follow the path "macOS Downloads\publicrelease", right-click the folder "001-79699 - 11.0.1 macOS Big Sur" while pressing Shift, select "Copy as path", then paste it into the console and click Enter.
7. I am getting the error:

`001-79699 - 11.0.1 macOS Big Sur is not in the available recovery package names:
recoveryhdupdate.pkg, recoveryhdmetadmg.pkg`
` `
`Ensure you're passing a proper recovery package.`

Am I doing something wrong or is there a problem with the app? I was thinking about adding recoveryhdmetadmg.pkg from Catalina, but I'm not sure if it will work correctly.

**Comment by uurcakmak** [comment]
Same here.

**Comment by soaring76** [comment]
You need to change to option R "recovery files only"... But if you currently do that, Big Sur is not available as download...  So that's where I'm stuck too...

**Comment by erenatas** [comment]
The easiest way for you is to install catalina, then upgrade with the packageassistant.pkg, or create a usb from the macos with createinstallmedia.

**Comment by soaring76** [comment]
Maybe the GibMacOs needs to be updated now to look for 11.00 and not 10.16 anymore....

**Comment by soaring76** [comment]
oh - and Big Sur on Hackintosh currently requires anyway a different procedure (Update onto Catalina):
https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#table-of-contents

**Comment by corpnewt** [comment]
There is no Big Sur recovery package in the software update catalog - as such, MakeInstall is incompatible with it.  Apple changed the way it delivers updates with Big Sur.

-CorpNewt

**Comment by mhrastegary77** [comment]
so the best way is to install catalina, then upgrade from OS settings???

**Comment by qwertym0nk** [comment]
> There is no Big Sur recovery package in the software update catalog - as such, MakeInstall is incompatible with it. Apple changed the way it delivers updates with Big Sur.
> 
> -CorpNewt

Maybe it would help to at least post a big warning that states "Big Sur and above are not supported for the MakeInstall." On the main page? Or did I miss that?

Would save a lot of time for folks.
