### ISSUE TITLE
 MakeInstall.bat got error when copy EFI folder at USB

### ISSUE THREAD

**Issue by tazik561** [corpnewt/gibMacOS#203]
After downloading last macos by gibMacOS when MakeInstall.bat  try to copy EFI folder  I got this error:
https://pasteboard.co/JE1oOgt.png

I have to record my desktop to see what is error because CMD closed immediately

**Comment by corpnewt** [comment]
How old is your gibMacOS?  I fixed this issue [some time ago](https://github.com/corpnewt/gibMacOS/commit/4083ca20785d96ef26eecac89c1c9e37532beb44), and the error you posted does not reflect the current code (line 112 does not contain the code listed in your screenshot as of [this commit](https://github.com/corpnewt/gibMacOS/commit/3c4f1d2b8d8c943cfdcedf662d6603aca0f0d321) back in July).  Please update your copy of gibMacOS and try again.

-CorpNewt

**Comment by tazik561** [comment]
I downloaded new released gibMacOS but  After downloading RecoveryHDMetaDmg.pkg with gibMacOS , by using MakeInstall.bat I am trying to make boot my 16gig my usb.

After selected my usb drive with `O` option , MakeInstall try to download OpenCore-0.6.4 RELEASE.zip.When downloading is finished and extracted, process stuck here ?

```
Gathering info...

- Got OpenCore-0.6.4-RELEASE.zip

Downloading...

Downloaded 3.79 MB of 3.79 MB (100.00%)

Extracting OpenCore-0.6.4-RELEASE.zip...

Gathering DUET boot files...

- boot
```

I am waited but the process did not pass from here and seems to stuck in - boot?

I don't get any error !! just stuck here?

https://pasteboard.co/JE6OhQr.png

**Comment by corpnewt** [comment]
It looks as though it's hanging while trying to download the DuetPkg files.  As long as you're not legacy booting, you can just Ctrl+C out of that, copy the EFI folder within the OpenCore release over to your EFI drive, then set it up for your hardware.

If I had to chance a guess as to why it's not currently working - I'd lean toward a potential network issue?  But as it's just hanging, I don't have a ton to go off.

-CorpNewt
