### ISSUE TITLE
It just works, I'm used to stuff not just working 😉

### ISSUE THREAD

**Issue by Barnacules** [corpnewt/gibMacOS#206]
As a career developer myself I know how frustrating it is to receive bugs that are hard to triage and fix so I decided to open an issue that you can just close as resolved since the bug is literally there wasn't a single bug throughout my experience and it worked exactly as expected and I'm hugely grateful 🤗

That is all,
Jerry (aka. Barnacules)
15 year Ex-MSFT SDET Microsoft
http://barnnerd.com

PS: I literally used this to make an a bootable thumb-drive to install a MacBook Air from 2012 that was cleaned off and wouldn't install via the internet recovery. But, now I'm going to build a Hackintosh because... Well... Why not! 😉

**Comment by Barnacules** [comment]
I am closing this issue because it was never an issue in the first place and just designed to make the developers feel happy and proud they made something that "Just worked". Developers are so under appreciated by the general public when they are pulling magical wands out of their backside and doing the impossible while the end user is just like "meh, it just works".

Merry Christmas 🎄

**Comment by hadenpf** [comment]
Love to see this! Even if some might consider it a little spammy I love seeing appreciation for people who make tools like this being thrown around

**Comment by Barnacules** [comment]
> Love to see this! Even if some might consider it a little spammy I love seeing appreciation for people who make tools like this being thrown around

I'd gladly take heat for being "spammy" or "annoying" if it means people get credit for their hard work and feel a little bit better about their day because of something I can do. Hell, I get attacked very day for doing nice things because the internet is full of unappreciated angry people. But, I'll gladly keep doing stuff like this if it makes even one person happy that made my day better by making something awesome even if it does get me death threats from closet 12yo hax0rs that are endlessly surfing the net to complain about stuff 😉

**Comment by corpnewt** [comment]
Thank you so much for the kind words!  I'm glad that your experience using my script was positive, and I really appreciate that you felt inclined to create this "issue" thread.  I hope that you and yours stay healthy and safe during the tough times that we've all been faced with of late - and that you continue to do nice things for internet strangers ❤️ 

-CorpNewt
