### ISSUE TITLE
Fails for Big Sur due to files missing from download step

### ISSUE THREAD

**Issue by mhucka** [corpnewt/gibMacOS#207]
I git cloned the repo to /tmp on a 2017 iMac running 10.13.6. I was able to create installers for Catalina without trouble, but when I try to produce one for Big Sur, it fails consistently. Steps to reproduce:

1. Run `gibMacOS.command`
2. Select option 1, which today is "macOS Big Sur 11.1 (20C69)" 
![image](https://user-images.githubusercontent.com/1450019/103243497-dfeaaa00-490e-11eb-8568-b708550e7ffc.png)
3. Let it do its thing. It downloads 12+ GB.
4. Quit out.
5. Run `BuildmacOSInstallApp.command`.
6. Drag the Finder icon for the downloaded directory onto the terminal window, as requested.
7. A missing-files error is printed: 
![image](https://user-images.githubusercontent.com/1450019/103245926-89816980-4916-11eb-9c76-1f2abdf4d4f6.png)

For whatever it's worth, here is what got downloaded by `gibMacOS.command`:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/1450019/103245955-a3bb4780-4916-11eb-80a6-f7c3fd2aa8ef.png">

**Comment by goldenbilla** [comment]
Actually i am able to boot into installation on big sur. downloaded through gibMac. But as i don't have internet i won't be able to install. 

BTW we have same MB and same 1225-V Ethernet. But it doesn't work in installation mode. Does it work for you?

**Comment by corpnewt** [comment]
With Big Sur, Apple changed the way the packages are delivered.  To get the .app, you do not need to run the `BuildmacOSInstallApp.command`, you instead just run the `InstallAssistant.pkg` and it will place the .app in your /Applications folder.

-CorpNewt

**Comment by mhucka** [comment]
Thanks for that info!
