### ISSUE TITLE
MakeInstall crashes when path its in contains space

### ISSUE THREAD

**Issue by MainTobias** [corpnewt/gibMacOS#209]
crashes if its in "C:\abv asgas\gibMacOS\" but not if it is in "C:\abvasgas\gibMacOS\"

**Comment by corpnewt** [comment]
Crashes immediately when you open it?  Or at a later point?

-CorpNewt

**Comment by MainTobias** [comment]
takes a few seconds asks for admin you grant it then it opens black python window and then both(bat and python window) close

**Comment by corpnewt** [comment]
I'll see what I can figure out - I updated the .bat starters for a number of scripts today - and I may have missed something.

-CorpNewt

**Comment by MainTobias** [comment]
okay thanks

**Comment by corpnewt** [comment]
I just pushed a commit that quotes the paths sent to `ctypes.windll.shell32.ShellExecuteW()` in utils.py that should fix it.

-CorpNewt

**Comment by MainTobias** [comment]
okay that works now

**Comment by corpnewt** [comment]
Glad to hear it.

-CorpNewt
