### ISSUE TITLE
Release is never found

### ISSUE THREAD

**Issue by wjk** [corpnewt/gibMacOS#223]
I’m running gibMacOS from genuine Intel Apple hardware. I am very interested in its ability to download past macOS releases. However, no matter what version I give (number or name), I get the following error (replace “Snow Leopard” as appropriate):

```
  #######################################################
 #           Downloading for Snow Leopard              #
#######################################################

'Snow Leopard' not found
```

This happens immediately after downloading the sucatalog file. Any pointers here? Thanks!

**Comment by chromer030** [comment]
I think old versions of macOS are not in apple official catalog.

**Comment by wjk** [comment]
@chromer030 Unfortunately, I think you’re right. Incremental testing reveals that High Sierra (and newer) download properly. Anything older gives me the error shown above. You may want to put a note in the README about this. Thanks nevertheless!
