### ISSUE TITLE
BuildmacOSInstallApp.command does not work with macOS Monterey download

### ISSUE THREAD

**Issue by ggoraa** [corpnewt/gibMacOS#242]
I downloaded full (12 gb one) package of macOS Monterey installer
I tried to make an installer using BuilmacOSInstallApp.command, but it does not work, the file arrangement is not the same as it expects

**Comment by zeroalphagit** [comment]
This youtube video shows how to do it: https://www.youtube.com/watch?v=UvHVpG26fkM&ab_channel=eFGaiD

**Comment by LeeBinder** [comment]
see https://github.com/corpnewt/gibMacOS/issues/139#issuecomment-723275624

Disclaimer: haven't tried myself

**Comment by Celtiore** [comment]
> https://www.journaldulapin.com/2019/06/01/image-bootable-mojave/

reply : 6200m to 14000m

**Comment by Celtiore** [comment]
> Well, i tried to do that, it makes an app, but then i try to make a bootable usb using createinstallmedia, it fails like here #204

replace : 6200m to 14000m
