### ISSUE TITLE
gibmacos cannot detect external hard dirve

### ISSUE THREAD

**Issue by jostimian** [corpnewt/gibMacOS#245]
I have an external hard drive but gibmacos cant find it. 
It is the disk2 in the image
![image](https://user-images.githubusercontent.com/38800640/141393605-2cf5a760-b684-419c-a606-28ba79fbcab9.png)
![image](https://user-images.githubusercontent.com/38800640/141393640-a2f9fa30-addf-4cc8-91e0-952fd881e09b.png)

**Comment by Masamune3210** [comment]
What partition style is the drive, gpt or legacy

**Comment by jostimian** [comment]
It it in mbr

**Comment by jostimian** [comment]
Sorry i did not know that i can use `d` to list all external and internal hard drives
