### ISSUE TITLE
Don`t see usb drive in MakeInstall.bat

### ISSUE THREAD

**Issue by Kuba112811** [corpnewt/gibMacOS#248]
I run MakeInstall.bat as administrator and it dont shows any drive I reconnected on all usb port of the laptop and it dont work even when turning on D function. My laptop is running on windows 11 the usb drive is for usb 3.0.

**Comment by Kuba112811** [comment]
I tried with another drive and it still dont work

**Comment by Kuba112811** [comment]
Tried on usb 2.0 and 3.0 ports

**Comment by artificialmusik** [comment]
I am running into this issue myself. I believe this has to do with what is being mentioned here.
I think the tool relies on WMIC and with Win 11, this feature was dropped. I believe it to be dropped in later Win 10 builds as well. At the moment I am unaware of a workaround.

https://winaero.com/microsoft-removed-the-wmic-tool-from-windows-11-dev-builds/
