### ISSUE TITLE
diskpart error on Windows 10 1903 and 1511

### ISSUE THREAD

**Issue by PedroxTheBest99** [corpnewt/gibMacOS#25]
Hello, i am trying to use gibMacOS to download Vanilla  macOS so i can make hackintosh,
but on both of my machines (my laptop running w10 1903 and my main pc running w10 1511)
i get his error:

"Using MBR...

DiskPart exited with non-zero status (1).  Aborting.

Press [enter] to return..."

if there is a fix for that or a way to skip format with diskpart, i would appreciate ^^

**Comment by corpnewt** [comment]
Are you running the script as admin?  The MakeInstall.bat script auto-elevates itself as diskpart needs admin perms.

Assuming you are, 95% of the issues people face with diskpart's formatting are related to one of the following (as disk part is *outrageously* picky):

* Windows is outdated
* The USB drive is unreliable
* Windows is improperly configured

You can try updating Windows, trying another USB drive, and trying another machine (beyond the 2 you've currently tested), but as this is not an issue with the script itself - I'll close the issue unless more information points toward MakeInstall.py/.bat being the culprit.

-CorpNewt

**Comment by PedroxTheBest99** [comment]
then, what's the configuration, also, sometimes the USB get corrupted when i use the makeinstall.bat (i already know how to fix that) and my main pc is on Windows 10 1511 and my laptop on 1903, so i could try on my laptop
