### ISSUE TITLE
Some needed files are missing

### ISSUE THREAD

**Issue by michelle1574** [corpnewt/gibMacOS#253]
I downloaded the latest build of MacOS in PublicRelease catalog.
There should be DMG file, but I can't find it.
Here is the screenshot:
![obraz](https://user-images.githubusercontent.com/70703680/155030833-b22dc302-fec7-4054-a634-77626c8f35fe.png)
I don't know why the diffrent issue that downloading doesn't work on slow internet had the DMG file.
Is that a diffrent build?

**Comment by corpnewt** [comment]
macOS 11 and 12 are distributed differently than prior versions, so this is normal for them.  If you're looking to get the BaseSystem.dmg|chunklist you may want to look into Acidanthera's [macrecovery](https://github.com/acidanthera/OpenCorePkg/tree/master/Utilities/macrecovery) script instead.

-CorpNewt
