### ISSUE TITLE
Lost original disk - or formatting failed!

### ISSUE THREAD

**Issue by jadderbao** [corpnewt/gibMacOS#258]
Gathering info...
 - Got OpenCore-0.7.8-RELEASE.zip
Downloading...
Downloaded 5.76 MB of 5.76 MB (100.00%)
Extracting OpenCore-0.7.8-RELEASE.zip...
Gathering DUET boot files...
 - boot
 - boot0
 - boot1f32
Lost original disk - or formatting failed!

**Comment by corpnewt** [comment]
Please do not open multiple issues unless actually needed.  Based on the three you've opened so far - it looks as though your USB drive may not be functioning properly as MakeInstall is failing to copy files and format the USB.  I'll try setting up a quick test USB to verify nothing has changed in OpenCore that would require scripting updates though.  I'll comment here when I've had a chance to test.

-CorpNewt

**Comment by corpnewt** [comment]
![image](https://user-images.githubusercontent.com/12772521/155521362-3db1cfad-7cee-4819-be1f-4c47b23f7fa0.png)

The entire process worked fine on my test USB - I would bet the issue lies either with your USB drive, or the local install.

-CorpNewt

**Comment by jadderbao** [comment]
oh,
