### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by joe-zhang3** [corpnewt/gibMacOS#26]
OS: windows 10 (inside a vm)

1. Run `MakeInstall.bat` as admin. 
2. Select `1g` - 1 is my USB stick. 
3. Error out. 

DiskPart succeeded in creating the specified partition.

    0 percent completed
    0 percent completed
    0 percent completed
    0 percent completed
    0 percent completed
  100 percent completed

DiskPart successfully formatted the volume.

Virtual Disk Service error:
The operation is not supported on a non-empty removable disk.

I used the same usb stick before the same way (but in another win 10 which is also inside a vm) it works fine. But have no idea why it failed now. 

Suggestions please.

**Comment by corpnewt** [comment]
95% of all MakeInstall issues are fixed by doing one of the following:

* Swap USB drives
* Update Windows
* Try another machine

Try those, and see if any fixes the issue.

-CorpNewt

**Comment by joe-zhang3** [comment]
@corpnewt  thanks for your reply, I will try and keep you updated.

**Comment by corpnewt** [comment]
Sounds good - best of luck

-CorpNewt

**Comment by joe-zhang3** [comment]
IT WORKS...

I updated my windows 10 to latest and I am able to pass that problems I met. thanks for your information.
