### ISSUE TITLE
Download stops at 99.93%  

### ISSUE THREAD

**Issue by Abdullah3553** [corpnewt/gibMacOS#269]
Hmmmmmm

I dont think there is anymore to Clearfield if i start to download recovery image on my pc it keep downloading until it reaches 99.39% and never end :D

**Comment by corpnewt** [comment]
From the main menu, you can toggle `I. Only Print URLs` to have the script print the URLs instead of trying to download them itself.  That way you can plug them into any browser/download manager of your choice.

-CorpNewt
