### ISSUE TITLE
 Installing Clover: Error communicating with github!

### ISSUE THREAD

**Issue by bill-fischer** [corpnewt/gibMacOS#27]
Hello. I am a new user of gibMacOS, so apologies if this is a known issue. I have followed the steps and am trying to build a USB using recovery media for Catalina. Everything seems to be working fine with MakeInstall.bat, but when it gets to "Installing Clover" it stops and presents the error message: "Error communicating with github!"

Any ideas? I have tried using a different PC and with both Admin and non-admin execution of the bat file. Any assistance appreciated! Thanks.
![Annotation 2019-10-18 144516](https://user-images.githubusercontent.com/28565159/67120064-84734700-f1b6-11e9-96d7-919f866eaa6d.png)

**Comment by 20Koen02** [comment]
I have this exact same issue. I have done this process several times now. Maybe something changed with the github url it's downloading from?

**Comment by corpnewt** [comment]
I won't be able to look into this for a bit - but I'll update when I get a chance to.

-CorpNewt

**Comment by bill-fischer** [comment]
Thank you @corpnewt ! Appreciate the feedback.

**Comment by 20Koen02** [comment]
@corpnewt @bill-fischer I worked out the issue. The latest release of cloverbootloader doesn't contain any assets (the compiled code) 
@bill-fischer for now, you can manually edit the code to use the previous version of clover which does contain the assets. Edit MakeInstall.py and replace the url of the `self.clover_url` variable in the `__init__()` function with `https://api.github.com/repos/CloverHackyColor/CloverBootloader/releases/20627694` (Release v2.5k-5096 of clover)

@corpnewt you know what to do. Check for assets and if none check the previous versions

**Comment by bill-fischer** [comment]
Wow, thanks, @20Koen02 . Never would have been able to do that myself. Thanks again!

**Comment by corpnewt** [comment]
Seems the latest one works now - but I also bulletproofed the code a bit in [this commit](https://github.com/corpnewt/gibMacOS/commit/2fd15e1319a1188d32ab681a0a18221eba03e2df).  Thanks for letting me know and being patient.

-CorpNewt

**Comment by bill-fischer** [comment]
@corpnewt thanks again, and thanks for creating such great software!

**Comment by bill-fischer** [comment]
Hi. seems to be happening again.

**Comment by corpnewt** [comment]
I just ran a quick test with the code MakeInstall.py uses (as I'm on macOS right now with py 3.7.5), and it located the download link just fine:
```py
>>> import downloader as dl
>>> d = dl.Downloader()
>>> import json
>>> clover_url = "https://api.github.com/repos/CloverHackyColor/CloverBootloader/releases"
>>> json_data = d.get_string(clover_url,False)
>>> j_list = json.loads(json_data)
>>> for j in j_list:
...     dl_link = next((x.get("browser_download_url", None) for x in j.get("assets", []) if x.get("browser_download_url", "").lower().endswith(".lzma")), None)
...     if dl_link:
...         break
... 
>>> dl_link
'https://github.com/CloverHackyColor/CloverBootloader/releases/download/5097/CloverISO-5097.tar.lzma'
```
May be a network issue on your side - or an outdated version of py that's being rejected by github?

-CorpNewt

**Comment by bill-fischer** [comment]
OK. Yeah. Makes sense. The error message is different this time. Just says it's unable to download. Regardless, thanks for checking it so quickly. Again, the software is great.
