### ISSUE TITLE
Catalog 

### ISSUE THREAD

**Issue by Dmitry5558** [corpnewt/gibMacOS#273]
Здравствуйте. А почему нет версии MacOS Sierra 10.12.6 ?

**Comment by casioforever** [comment]
Macos Sierra v10.12.6 Released in 26-09-2019
![Macos Sierra](https://github.com/corpnewt/gibMacOS/assets/148558396/9efaaf13-8d90-4d5a-b572-3a45035a8f51)
However, All Catalogs Were Updated To Offer MacOS High Sierra 
(The Oldest Index 10.6 Doesn't Include Any Releases Of MacOS Sierra)
![macos catalog](https://github.com/corpnewt/gibMacOS/assets/148558396/303ed5ae-f188-4de5-b2d6-bd3cc25ab303)
That Doesn't mean that All Old Version Were Omitted From Apple Servers
Here Are The Direct Links Of Apple Old Versions Of MacOS:
MacOS Sierra v10.12 
http://updates-http.cdn-apple.com/2019/cert/061-39476-20191023-48f365f4-0015-4c41-9f44-39d3d2aca067/InstallOS.dmg
MacOS Sierra v10.12.6 Combo Update :
https://updates.cdn-apple.com/2019/cert/041-90765-20191011-837e856d-b522-4865-b64c-641048ed77c4/macOSUpdCombo10.12.6.dmg
MacOS X El Capitan v10.11 : 
http://updates-http.cdn-apple.com/2019/cert/061-41424-20191024-218af9ec-cf50-4516-9011-228c78eda3d2/InstallMacOSX.dmg
MacOS X El Capitan v10.11.6 Combo Update : 
https://updates.cdn-apple.com/2019/cert/041-88497-20191011-7c5dfb9c-fb81-4d22-afe6-230cd077c850/OSXUpdCombo10.11.6.dmg
MacOS X Yosemite v10.10 : 
http://updates-http.cdn-apple.com/2019/cert/061-41343-20191023-02465f92-3ab5-4c92-bfe2-b725447a070d/InstallMacOSX.dmg
MacOS X Yosemite v10.10.5 Combo Update : 
https://updates.cdn-apple.com/2019/cert/041-88380-20191011-c5bbb3ec-7f37-4b44-8cb4-753810df3edc/OSXUpdCombo10.10.5.dmg
