### ISSUE TITLE
Please Add Option For Using Locally Downloaded Builds of (Opencore, Clover)

### ISSUE THREAD

**Issue by casioforever** [corpnewt/gibMacOS#282]
Dear @corpnewt,
Some Environments Doesn't Have An Active Internet Connection, That's Why It Would Be Very Useful If The Users In Such Places, Can Put Their Downloaded Copies (From Github Or Elsewhere) Inside Main Folder of gibMacOS. Also The Tool Requests Files Ended With (*.tar.lzma) Which Isn't Helpful When Downloading The Latest Version Of Clover (V5155) Which Doesn't Have Such File For Its Relevant Version. gibMacOS Only Grabs r5153 of CloverHackyColor (Unlike Latest version of Clover-Builder Which Can Be Grabbed Successfully). I'd Be Grateful, If Your Amazing Tool Got Updated With USB Creation Using Locally Downloaded Builds Of Clover/Opencore. Thanks for Amazing Tool @corpnewt

**Comment by corpnewt** [comment]
Can you test out [this commit](https://github.com/corpnewt/gibMacOS/commit/8f8cf2ff759ddd8d288d62e1e95553e508008fc6) and see if that can get the newer Clover versions - as well as allows the local archives?  I've done some rather quick preliminary tests, but have not verified everything yet.

I added a new option in the main menu (`L`) which will prompt for a local archive - but if you intend to pass it a Clover archive, it still requires the `C` argument.  Clover archives can be either `.tar.lzma` or `.7z` - OpenCore archives are expected to be `.zip` files.

-CorpNewt

**Comment by casioforever** [comment]
Hi @corpnewt 
It's Me, Again :)
Your Modification Works As You Can See In That Screenshot
![local Copy](Https://github.com/corpnewt/gibmacos/assets/148558396/ab9c1b40-ebac-4732-8f22-61b04b112390)
Just Some Retouches Here And There :

1. The Problem #281 Can Now Be Closed, Which Caused By Following Syntax 
**[drive Number] [options] R[clover Revision (Optional)]**
-----------that Line Needs To Be Replaced With-------------
**[drive Number] [options] R[opencore Revision (Optional)]**
# The Line Shows That The Default Bootloader Will Be Clover,
Which Is Not True, Because Clover Needs Option C To Be Used.

2. When Using The Following Syntax (Without L Option) :
**[drive Number] [options] R[clover Version (Optional)]**
The Result Always Be Based On Clover Versions By **slice (Chc)**,
Can You Optimize Your Code To Compare Input Before Applying
The Final Command? I Mean **[drive Number] [options] R (N)** 
If N<=5122 Then The Tool Gets The Version Made By Dids. (Clover Wo. Oc Augments).
If N>5122 Then The Tool Gets The Version Made By Slice (Clover W. Oc Augments).

3. Can You Please Integrate Ddrelease64.exe Into Your Tool ?
Downloading That Component On Every Time I Need To Use 
Your Tool Is Really Annoying Task. I Thought The Bug Was On 
Your Side Until I Discovered Its Absence From Your Files.

4. Can You Integrate Rufus 2.18 (Xp, Vista) Or 3.22 (7sp1+) ?
Using Your Tool **again** For Mbr Formatting Causes This Strange Error 
![diskpart 2147942833](Https://github.com/corpnewt/gibmacos/assets/148558396/dd28514b-9d15-40b3-9edd-6c9ae2aac30f)
And When Used **again** For Gpt Formatting Causes This Strange Error
![diskpart 2147942487](Https://github.com/corpnewt/gibmacos/assets/148558396/cd101678-f6b4-40c2-8e81-6def67a0e14d)
This Errors Can Be Solved Using Rufus. If You Can't Integrate It, Do You Have A Solution?
**finally, Thanks For Quick Response And For Hearing Carefully To Your Community.**
Have A Nice Day.

**Comment by casioforever** [comment]
Hi @corpnewt,
Thanks for Quick Response
1. This Suggestion Would Be Very Nice, Win-Win For All Sides :
```Usage: [drive number][options] r[Clover revision (optional), requires C]
  (eg. 1B C r5092)
```

2. Clover-builder R5122 (Made By Dids) Doesn't Contains Any Opencore Modifications, I've Faced Many Hackintoshers Which Got Stuck In Problems Because Of Instability Of Cloverhackycolor After Being Augmented With Opencore In Its Recent Releases By (Slice) Such As R5155. This Can Be Resolved By Your Latest Modification Of Makeinstall (i mean providing dids releases locally through your amazing tool). But, For The Integrity Of Your Code, It'd Be Awesome If Your Tool Can Be Automated To Search For Revisions According To Number 5122.

3. Regarding Ddrelease64 & Rufus, I Understand Your Concerns. At The End, You Know About Software Licenses Better Than Me.

4. No Need To Remove Diskpart Scripts, It Is The Only Way To Integrate Bootloaders Successfully On Usb Flash Drive. Trust Me, Among Many Tools To Create MBR\GPT Partition Scheme For Opencore\clover Usb Loader, The Diskpart Hits The Mark Precisely.
I Just Can't Override Its Errors When Using Your Tool Again, And Again. Thus, I Run For The Help Of Rufus Tool. 
If You Found A Way To Format Usb Driver **Before** Using Diskpart Commands, No One Will Complain From Diskpart Errors Anymore.

**Comment by corpnewt** [comment]
Alright - as of [this commit](https://github.com/corpnewt/gibMacOS/commit/bdd40299076954c8a5808bcde4a6ca67f5c01602) it should pull from the proper place depending on the `r[version]` passed.  I also updated the example usage in the main menu to clarify the `r[version]` section is for Clover specifically.

I can look into skipping portions of the `diskpart` code in the event you've already formatted a disk I suppose - that's not something I'll likely be able to implement quickly though, and will likely take a fair bit of time.  Currently, there's the `B` option which only attempts to install the bootloader to the first partition of the disk - but I could also implement some other flag to skip attempting to format.

Please let me know if the above commit works as expected, and I'll see if there's a sane way to skip using `diskpart` to format.

-CorpNewt

**Comment by corpnewt** [comment]
Alright - that wasn't as painful as I thought.  I fixed a couple bugs, updated some singleton comparisons, and added another main menu flag (`F`) that allows skipping formatting of the drive.  Due to the way dd works though, it still **requires** the drive's first partition be FAT32 and second be RAW.

The commit is [here](https://github.com/corpnewt/gibMacOS/commit/1c4676d9258ba3d0e8d43c8f8d6e96beee160a2d) if you want to check it out.

I imagine that covers most of the requested additions - please let me know if you have more questions.

-CorpNewt

**Comment by casioforever** [comment]
Hi @corpnewt 
Here Is My Timeline of Testimonials :
1.
![First Screen](https://github.com/corpnewt/gibMacOS/assets/148558396/a8e8f589-33d0-4cf4-ab34-158309c893f1)
2. Writing 6C r5122 (CURRENT PARTITION SCHEME :MBR)
![6C r5122 (MBR)](https://github.com/corpnewt/gibMacOS/assets/148558396/363d3220-42e2-427b-8260-6468fc4412ce)
3. Writing 6FC r5155 (CURRENT PARTITION SCHEME :MBR)
![6FC r5155 (MBR)](https://github.com/corpnewt/gibMacOS/assets/148558396/51dfb18c-65dc-4c01-856a-bc394a92bb36)
4. VVV (Verification Via Vmware) (CURRENT PARTITION SCHEME :MBR)
![VM 6FC r5155 (MBR)](https://github.com/corpnewt/gibMacOS/assets/148558396/efecf2d4-d6ce-40ca-b3cf-78cdbf2b12ac)
5. Writing 6GC r5122 (CURRENT PARTITION SCHEME :MBR) | Solved by Un-plug USB Then Re-plug USB
![DISKPART 2147942833](https://github.com/corpnewt/gibMacOS/assets/148558396/f065b31c-4795-41c3-a343-d89c6ab4ab35)
6. Writing 6GC r5122 (CURRENT PARTITION SCHEME :MBR)
![6GC r5122 (GPT)](https://github.com/corpnewt/gibMacOS/assets/148558396/2324810e-22c3-4d71-a23a-f704352c8866)
7. Writing 6FC r5155 (CURRENT PARTITION SCHEME :GPT)
![6FC r5155 (GPT)](https://github.com/corpnewt/gibMacOS/assets/148558396/6429d067-25ab-4831-b1d6-391b92411f40)
8. VVV (Verification Via Vmware) (CURRENT PARTITION SCHEME :GPT)
![VM 6FC r5155 (GPT)](https://github.com/corpnewt/gibMacOS/assets/148558396/20982387-b129-4cde-adaf-302274c898d5)
Notes :
A. No Usage of Rufus (At Alllllllllllllllll)
B. No Usage of Options B, E, U, L & D
What Do You Think ?
-Casio4Ever

**Comment by corpnewt** [comment]
I take it that aside from the instance where `diskpart` failed to format, the rest went alright?

-CorpNewt

**Comment by casioforever** [comment]
> I take it that aside from the instance where `diskpart` failed to format, the rest went alright?

The Diskpart Only Fails In Very Specific Condition :
1. When 200 Mb Partition Only Is Visible
2. When Converting Usb From Diskparted (Mbr) To Diskparted (Gpt)

**Comment by corpnewt** [comment]
Glad to hear it.  I'll go ahead and mark this issue thread as solved then.

-CorpNewt
