### ISSUE TITLE
Makeinstall.bat Exits Before Completing The Installation Of Locally Downloaded Opencore Package

### ISSUE THREAD

**Issue by casioforever** [corpnewt/gibMacOS#283]
Like The Title Says
[drive Number] L 
Exits Before Printing This Message
![Opencore - Downloaded](https://github.com/corpnewt/gibMacOS/assets/148558396/d2f6c225-8eab-453e-a569-cecea1abebc5)
One  More Thing, Is There Any Ability To Install Debug Versions Of Opencore ?

**Comment by corpnewt** [comment]
Could you run the .bat file directly via cmd.exe and see if it's throwing an error?  I'm betting something is amiss - perhaps I've missed a check with the other changes I'd made or similar and running it through cmd prevents the window from closing if it bails.

To do that, you can:

1. Open a new cmd.exe window as administrator
2. Navigate to the gibMacOS folder in Explorer
3. Click the address bar and copy the address
4. In the cmd.exe window, type `cd` followed by a space, then paste the address you copied and press enter
5. Type `MakeInstall.bat` and press enter
6. Go through the usual steps you'd take - and send a screenshot of where the script bails.

Regarding the question of debug OC builds - the only way currently would be to pass it as a local file.  I could likely look into adding the option for downloading debug, but I'm not sure when I'll be able to.

-CorpNewt

**Comment by casioforever** [comment]
Dear @corpnewt 
Here Are The Information You Asked For :
1. Running GibMacOS From CMD As Administrator
![Opencore debugging cmd 1](https://github.com/corpnewt/gibMacOS/assets/148558396/f7cd9af3-b6bc-4450-a3a0-444065151e87)
2. The Tool Running The Process Of Installing Recovery Pkg On Usb :
![Opencore debugging cmd 2](https://github.com/corpnewt/gibMacOS/assets/148558396/9a6f40c1-a3cf-49de-8bbe-932927fb81e2)
3. The Verbose Log After GibMacOS Making its Adjustment to Opencore :
![Opencore debugging cmd 3](https://github.com/corpnewt/gibMacOS/assets/148558396/e5c16f2b-8811-4a9d-b8af-ed34c9c3385f)

**Comment by corpnewt** [comment]
Ahh - I know what's happening.  The DuetPkg files changed at some point - so those have been downloaded separately from a specific commit of OpenCorePkg ([from here](https://github.com/acidanthera/OpenCorePkg/raw/870017d0e5d53abeaf0347997da912c3e382a04a/Utilities/LegacyBoot/)) - and if you're running without internet, they're not available.  I suppose what I can do is first check the downloaded/locally provided zip to see if the files needed exist - and if not, try downloading from that specific commit.  If neither works - then I'll just have it create a UEFI-only installer as there's not much else I could do.

-CorpNewt

**Comment by corpnewt** [comment]
Alright, as of [this commit](https://github.com/corpnewt/gibMacOS/commit/e8a8f8e20aa72ebf759ca682d10ca8fdee9ac7f3), the script should first look in the downloaded/locally passed archive for the DUET related files - and if found, will use those.  If not found, it will attempt to download them.  If that fails, then it just doesn't try to use them.  I also fixed some pathing when using a local OpenCore zip that's quite old as that has a different folder structure.

At some point, I may get around to looking at having it be able to download the debug build - but I'm not sure when I'll be able to.

-CorpNewt

**Comment by casioforever** [comment]
I have good news for you :
> Ahh - I know what's happening. The DuetPkg files changed at some point - so those have been downloaded separately from a specific commit of OpenCorePkg ([from here]
> 
> -CorpNewt
The Big One Can Be Simplified In This Tiny Little [commit]
(https://github.com/acidanthera/OpenCorePkg/commit/ce1c67b6852c5a5a22f76bfd1a135852a7e795df) 

The Awesome One Is Your Tool Now Can Install Debug Releases Of Opencore Using L Option 
Can You Tell The Difference Between These Screenshots ?

1

![Opencore debugging cmd 4 (6L)](https://github.com/corpnewt/gibMacOS/assets/148558396/15239c06-f769-407b-b537-dc8be62afc99)

2

![Opencore debugging cmd 5 (6L)](https://github.com/corpnewt/gibMacOS/assets/148558396/78c8f79d-8f19-4c5b-810c-1e0aa033d6d4)

**Comment by corpnewt** [comment]
> The Big One Can Be Simplified In This Tiny Little Update [[Here](https://github.com/acidanthera/DuetPkg/raw/master/README.md)]

Well, originally the `boot` file was included with the LegacyBoot files (as seen [here](https://github.com/acidanthera/OpenCorePkg/blob/870017d0e5d53abeaf0347997da912c3e382a04a/Utilities/LegacyBoot/boot)), but was then swapped to just the source for it (as seen [here](https://github.com/acidanthera/OpenCorePkg/tree/master/Utilities/LegacyBoot)), which is intended to be built when building OpenCore.  This means that for OpenCore versions that were released *before* that change (OC 0.5.9 and prior) aren't packaged with the legacy files.

The script's workaround in that case is to attempt to download the legacy boot files from the specific github commit, and if there's no internet access or they cannot be downloaded, the script just falls back to creating a UEFI-only USB with no legacy support.

> Can You Tell The Difference Between These Screenshots ?

I wasn't too concerned about it not being able to install debug when providing a local .zip as the folder structure is the same as release - but I was under the impression you were asking for a specific flag in the menu to have it download the debug build specifically.  For that functionality, I'd have to write more code - and that depends on my schedule (and mood lol).

Thanks for testing - please let me know if you find other oddities.

-CorpNewt

**Comment by casioforever** [comment]
> I was under the impression you were asking for a specific flag in the menu to have it download the debug build specifically.
imaging you have the tool that comes in all shapes & sizes !.
 if you wish to do that please hurry before I had to Re-write 
 the (mastering GibMacOS) to include your latest additions :)
