### ISSUE TITLE
Use Opencore instead of Clover. 

### ISSUE THREAD

**Issue by ngabroger** [corpnewt/gibMacOS#287]
![image](https://github.com/corpnewt/gibMacOS/assets/99066995/98c59b7b-23e8-4799-b4be-a9c25d44b855)

**Comment by corpnewt** [comment]
Not sure what this issue is intending.  MakeInstall uses OpenCore by default, but has options to use Clover if the user desires.  Closing as it is not actually an issue.

-CorpNewt

**Comment by casioforever** [comment]
@corpnewt May be he asks if the tool can deal with only 1 partition with a very low empty space ?
