### ISSUE TITLE
Are the apple URL's no longer working?

### ISSUE THREAD

**Issue by JA-Marshall** [corpnewt/gibMacOS#289]
I've tried to start downloading a few different OS's and they seem to be timing out,  they download up to a certain point, then the progress stops at a certain percentage but doesn't give any indication that its failed other than the file sizes being way too small.

I tried to download directly from the URL's and the same thing is happening, is apple throttling / stopping people from downloading directly?

![image](https://github.com/corpnewt/gibMacOS/assets/9871373/2387a5ab-4971-4ced-8941-3fd3e4dbbf9f)

**Comment by JA-Marshall** [comment]
I managed to download the files in the browser but there's some weird limited going on, It downloads about 500MB then would hang and I'd have to restart the download, don't think its my internet as I'm downloading other large files fine.

**Comment by corpnewt** [comment]
I just tested here and I'm getting mixed results.  Seems I can download Monterey and Ventura just fine (they both downloaded completely as well, not just partially):

![image](https://github.com/corpnewt/gibMacOS/assets/12772521/620329ca-2c31-4dc7-8613-329becba4668)

![image](https://github.com/corpnewt/gibMacOS/assets/12772521/6d2b2026-3bdf-49ff-a526-38e166c2cc69)


But Sonoma appears to be stalling out at random points - similar to your experience.  I'm inclined to believe it's an issue on Apple's end at the moment, and something that they may fix.

I'll leave this issue open for now - but I don't think it's an issue with gibMacOS itself.

-CorpNewt

**Comment by corpnewt** [comment]
Yeah - seems to be working fine today, so I assume it was an issue on Apple's end:

![image](https://github.com/corpnewt/gibMacOS/assets/12772521/d233e78b-d098-4a81-8424-e3034aa35a7e)

I'll close the issue as it doesn't seem to be a problem with gibMacOS.

-CorpNewt
