### ISSUE TITLE
Malicious object detected !

### ISSUE THREAD

**Issue by casioforever** [corpnewt/gibMacOS#292]
![Malicious object detected](https://github.com/corpnewt/gibMacOS/assets/148558396/ad6ea091-faa9-445a-bb45-562ce4ff487c)

Event: Malicious object detected
Application: Windows Command Processor
User: ******-*******\*******
User type: Initiator
Component: System Watcher
Result description: Detected
Type: Trojan
Name: PDM:Trojan.Win32.Generic
Threat level: High
Object type: Process
Object path: F:\System\Desktop\gibMacOS-master
Object name: MakeInstall.bat
Reason: Behavior analysis
Databases release date: Today, 2/13/2024 1:30:00 PM
MD5: 4D8361EED863D37930FF959FDD9803A0

**Comment by corpnewt** [comment]
Does that also throw an error for `gibMacOS.bat`?  It and `MakeInstall.bat` are identical - and while I've updated them recently to work around some long standing bugs, and work through some GitHub related issues with line endings - they're not malicious.  I'm inclined to believe that is detecting a false positive.

-CorpNewt

**Comment by casioforever** [comment]
> Does that also throw an error for gibMacOS.bat? 

Nope

> they're not malicious. I'm inclined to believe that is detecting a false positive.

I Know. Just Leave A Note For New Users To Add Them To Exclusions.
![Malicious object detected](https://github.com/corpnewt/gibMacOS/assets/148558396/2867a118-508a-4b77-8522-5375871c19aa)

**Comment by corpnewt** [comment]
I wonder if it flagged it because it's a batch script, it installs something, and it has "install" in the name?  I've had other scripts I've written get flagged for their name, not their contents before.  If it becomes a common issue, I'll look at changing the name - but for the time being I'll leave it as-is.  Thank you for bringing it to my attention though.

-CorpNewt

**Comment by casioforever** [comment]
> I wonder if it flagged it because it's a batch script, it installs something, and it has "install" in the name? I've had other scripts I've written get flagged for their name, not their contents before. If it becomes a common issue, I'll look at changing the name - but for the time being I'll leave it as-is. Thank you for bringing it to my attention though.
> 
> -CorpNewt

You're Welcome
