### ISSUE TITLE
Check PATH for tools

### ISSUE THREAD

**Issue by radj307** [corpnewt/gibMacOS#293]
`MakeInstall.py` currently only checks the default Program Files directory for 7zip.
I have it installed in a non-standard location on my computer, so it failed *(and also failed to install it as the link may be dead)* but I do have it on my PATH.

The PATH should probably be checked before assuming the location of a program.

**Comment by corpnewt** [comment]
Hey there - I'm not sure I'll get to it tonight, but I should be able to leverage `where.exe` to check the PATH var, and then fall back to the expected install location pretty easily.

-CorpNewt

**Comment by corpnewt** [comment]
It was actually easier to set up than I expected - please check if this commit works for your use-case: https://github.com/corpnewt/gibMacOS/commit/c01e345f33e51802ac490b5c1847d6b337beabe7

-CorpNewt
