### ISSUE TITLE
Creating Full MacOS USB Installer

### ISSUE THREAD

**Issue by casioforever** [corpnewt/gibMacOS#294]
Is There Any Chance To Create The Full Installer of MacOS Instead Of Recovery Installer ? 
----
[This Tool](https://github.com/doesprintfwork/MakeInstallmacOS) makes the following :
----
> Pack files to SharedSupport for converting Internet Recovery Installer to a Full Installer
> Pack files to a full Install macOS Application (Only in macOS)
----
Is There Any Hope for GibMacOS To Prepare The Files To (SharedSupport) 
Include (Renaming InstallESDDmg.pkg to InstallESD.dmg) ?

Also, Is There Any Hope To Copy the Final Result to MakeInstall-Prepared USB Disk ? 

All I'm Trying To Say, Why The End-User Can't Get The Most of GibMacOS To Make The Full MacOS Installer on His USB ? 
Instead of Creating The Recovery Installer of MacOS At The End of The Day ?

**Comment by corpnewt** [comment]
You can build an offline installer with files from gibMacOS and macrecovery.py by leveraging my [UnPlugged](https://github.com/corpnewt/UnPlugged) script.  The process works in macOS, Windows, and Linux.

-CorpNewt

**Comment by casioforever** [comment]
Thanks For Your Quick Reply, 
To Rephrase My Request, I'm Asking If You Had Enough Time To Implement Such A Great Feature Directly Into GibMacOS, 
If You Don't Have it, It's O.K . I Really Appreciate What You've Done So Far To Make Such A Tool. Keep Up The Good Work.
I'm Already Working on An Updated Version Of **GibMacOS Guide**, Your Response Inspired Me With A Great Idea....

-Casio4ever
