### ISSUE TITLE
Does not accomodate for a user having Python 2.7 installed

### ISSUE THREAD

**Issue by DuIslingr** [corpnewt/gibMacOS#3]
I was trying to use this via the vanilla amd guide and I kept getting not found in path even after 32 bit and 64 bit versions were installed. I even verified that they were added to path and rebooted. So I opened a separate terminal and ran python and it opened a 2.7 instance so i just uninstalled it and the script started working after that.

Specifically on Windows 10.

**Comment by corpnewt** [comment]
Fixed by routing stderr to stdout and verifying the returned string starts with "python":
```
:checkpy
REM Get python location
set "python="
FOR /F "tokens=* USEBACKQ" %%F IN (`python -V 2^>^&1`) DO (
    set "t=%%F"
    if /i "!t:~0,6!" == "python" (
        set "python=%%F"
    )
)
```
