### ISSUE TITLE
ImportError: cannot import name 'LegacyVersion' from 'packaging.version'

### ISSUE THREAD

**Issue by xavierbaez** [corpnewt/gibMacOS#301]
Hello
I have python@3.13 using homebrew
I also installed pipx and pipx install xattr
I also manually linked/usr/local/bin/python so it links to python3
python --version outputs 3.13 if using env
as far as I know python is correctly installed and working
File "./installinstallmacos.py", line 47, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/usr/local/lib/python3.13/site-packages/packaging/version.py)

During handling of the above exception, another exception occurred:

**Comment by corpnewt** [comment]
I think you may be in the wrong GitHub repo.  There is no `installinstallmacos.py` file in this project, nor that `from packaging.version import LegacyVersion` line.

-CorpNewt
