### ISSUE TITLE
After downloading, make into one DMG

### ISSUE THREAD

**Issue by Jayden000** [corpnewt/gibMacOS#31]
Is there a way to make all the files into one DMG to be able to send to friend online. When I run MakeInstall it seems like it is only burning to a USB Drive.

**Comment by corpnewt** [comment]
If you look through [the code](https://github.com/corpnewt/gibMacOS/blob/master/MakeInstall.py#L317-L327), you can see that the script extracts the BaseSystem.dmg from within the recovery package -> recovery dmg.  There's no need to create an image - as the image already exists within the recovery package. The two commands used to extract it (with path placeholders) are as follows:
```
7z e -txar path/to/recovery.pkg *.dmg
7z e *.dmg */Base*.dmg
```
Regardless, closing as it's not an issue with the script.

-CorpNewt

**Comment by Jayden000** [comment]
So this "BaseSystem,dmg" which already appears to be in the folder (see attached file) 
![image](https://user-images.githubusercontent.com/23621862/67621989-725f5d00-f7e3-11e9-8b8d-2ae902fa1027.png) will work to install macOS, I basically just want everything that is burned onto the USB into one DMG file (includes clover, etc)
