### ISSUE TITLE
Error while Executing MakInstall.py -- run module has no attribute Run()

### ISSUE THREAD

**Issue by AshishAYadav** [corpnewt/gibMacOS#32]
#######################################################
 #                    Verifying OS                     #
#######################################################

Verifying OS name...
 - Name = NT
Verifying OS version...
 - Version = 18362

18362 >= 9600, continuing...
Traceback (most recent call last):
  File "MakeInstall.py", line 705, in <module>
    w = WinUSB()
  File "MakeInstall.py", line 12, in __init__
    self.d = diskwin.Disk()
  File "C:\Users\***\Desktop\gibMacOS\Scripts\diskwin.py", line 8, in __init__
    self.r = run.Run()
AttributeError: module 'run' has no attribute 'Run'

**Comment by corpnewt** [comment]
Discussed in [this issue](https://github.com/corpnewt/gibMacOS/issues/21) already:
> Ok, I found the issue, it was package name issue. Anaconda3's interpreter (which I don't use often) also has a package named run.py.

You likely have a python distribution/interpreter with a built-in "run.py" module.  If you're not using that specifically, you can uninstall python and have the script install it for you (which will just be the standard library).  Alternatively - you can install another version of python, and use that explicitly to run the script to avoid class collisions.

-CorpNewt

**Comment by AshishAYadav** [comment]
Renamed run file to Run and replaced in MakeInstall.py and worked

**Comment by corpnewt** [comment]
Glad to hear that fixed it 👍
