### ISSUE TITLE
macOS Catalina 10.15.2 not showing in any catalog

### ISSUE THREAD

**Issue by arn95** [corpnewt/gibMacOS#34]
Title says it all. Is this an issue with parsing or Apple hasn't put it in their catalogs yet?

EDIT: It is in catalog.

**Comment by Exonical** [comment]
Can confirm this, not showing in the downloader but it is in the catalog.

**Comment by corpnewt** [comment]
Appears to show up in the recovery updates - just not the full install (likely because Apple doesn't have a full 10.15.2 beta 1 installer in the catalog):
![image](https://user-images.githubusercontent.com/12772521/68442797-b9603180-0197-11ea-82c8-b62abd64802a.png)
