### ISSUE TITLE
How do i fix this?

### ISSUE THREAD

**Issue by ddm4313** [corpnewt/gibMacOS#37]
#######################################################
 #               Erasing With DiskPart                 #
#######################################################

Using MBR...

DiskPart exited with non-zero status (1).  Aborting.

**Comment by corpnewt** [comment]
Nearly all of MakeInstall issues are fixed by one or more of the following:

* Swap USB drives
* Update Windows
* Try another machine

Try those, and see if any fixes the issue.

-CorpNewt

**Comment by ddm50** [comment]
Tried both of  those didn't work, however I ran .py files in administrator and it worked but now it's  Extracting Recovery dmg...
An error occurred extracting: 2

**Comment by corpnewt** [comment]
> An error occurred extracting: 2

Likely either an old version of 7z - or the download didn't complete correctly or is corrupt.

-CorpNewt

**Comment by jmmousee** [comment]
I am having the same issue   #######################################################
 #               Erasing With DiskPart                 #
#######################################################

Using MBR...

DiskPart exited with non-zero status (1).  Aborting.

I updated and switched USB ports. I do not have another system to try it on.

**Comment by corpnewt** [comment]
Yeah - unfortunately this is an issue with DiskPart, Windows, a third party partitioning tool, and/or the USB drive - so it's not within the scope of this script, nor anything I could likely fix at the python level.  All the script is doing during that error is piping a script to DiskPart to erase the target USB disk.  The error itself is not related to python, nor the MakeInstall script.

-CorpNewt
