### ISSUE TITLE
Other version in gibMacOS

### ISSUE THREAD

**Issue by Emanuele-1998** [corpnewt/gibMacOS#38]
How download other version such as High Sierra,Sierra,El Capitain and Yosemite? I try download the dmg of Yosemite but not have the necessary files for make a USB in windows. How solve it?

**Comment by corpnewt** [comment]
Currently gibMacOS only shows products available in the sucatalog from Apple. At some point I may gather links for legacy OS versions and hardcode them - but I have not done that as of yet.

-CorpNewt

**Comment by Emanuele-1998** [comment]
will this feature be released soon to download it? because this software is very complete and I really like it for not using the virtual machine from windows and when it will be released this correction will be applied also for macOS?

**Comment by Emanuele-1998** [comment]
@corpnewt will this feature be released soon to download it? because this software is very complete and I really like it for not using the virtual machine from windows and when it will be released this correction will be applied also for macOS?

**Comment by corpnewt** [comment]
I currently have no ETA on when that will be added.

-CorpNewt
