### ISSUE TITLE
KeyError: 'partitions'

### ISSUE THREAD

**Issue by shrishadas** [corpnewt/gibMacOS#4]
I just was following AMD OSX Vanilla  install guide and everything was fine until I began making usb installation drive. After script completed downloading clover I'm getting this error: Downloaded 2.70 MB of 2.70 MB (100.00%)
Extracting CloverISO-4934.tar.lzma...
Extracting CloverISO-4934.tar...
Extracting EFI from Clover-v2.4k-4934-X64.iso...
Extracting boot0af from Clover-v2.4k-4934-X64.iso...
Extracting boot1f32alt from Clover-v2.4k-4934-X64.iso...
Extracting boot6 from Clover-v2.4k-4934-X64.iso...
Traceback (most recent call last):
  File "c:\Users\shrisha\Desktop\gibMacOS-master\MakeInstall.py", line 763, in <module>
    w.main()
  File "c:\Users\shrisha\Desktop\gibMacOS-master\MakeInstall.py", line 759, in main
    self.diskpart_erase(selected_disk, use_gpt)
  File "c:\Users\shrisha\Desktop\gibMacOS-master\MakeInstall.py", line 346, in diskpart_erase
    self.select_package(disk)
  File "c:\Users\shrisha\Desktop\gibMacOS-master\MakeInstall.py", line 368, in select_package
    self.select_package(disk)
  File "c:\Users\shrisha\Desktop\gibMacOS-master\MakeInstall.py", line 442, in select_package
    self.dd_image(disk, os.path.join(temp, hfs))
  File "c:\Users\shrisha\Desktop\gibMacOS-master\MakeInstall.py", line 480, in dd_image
    self.install_clover(disk)
  File "c:\Users\shrisha\Desktop\gibMacOS-master\MakeInstall.py", line 573, in install_clover
    part = self.d.disks[str(disk["index"])]["partitions"].get("0",{}).get("letter",None) # get the first partition's letter
KeyError: 'partitions'
Could someone explain me please what I'm doing wrong. And I executing all scripts from Administrator command line window.

**Comment by corpnewt** [comment]
Seems this error could be caused by either a touchy USB drive, or some third party disk management soft (Windows is terribly picky throughout this process, unfortunately).  The USB gets partitioned, but no partitions are located.  The script uses the following command to locate the partitions on each disk:
```
wmic path Win32_LogicalDiskToPartition get antecedent,dependent
```
If the USB's partitions aren't listed there, the script will not find them.

I'm not sure of a fix currently - but if I find one, I'll update this.

-CorpNewt

**Comment by corpnewt** [comment]
Still no definitive "fix" found for this particular issue - the best advice I can give is to try another USB drive or another machine.  I updated the script to respond to a lack of partitions after reformatting and fail more gracefully, but there doesn't appear to be much more I can do beyond that.

-CorpNewt
