### ISSUE TITLE
Download macOS no RECOVERY 

### ISSUE THREAD

**Issue by Emanuele-1998** [corpnewt/gibMacOS#40]
I downloaded the complete catalina system then NO RECOVERY  but I can't understand why afterwards with the installer it asks me for an internet connection

https://imgur.com/a/B2Vow1F

**Comment by corpnewt** [comment]
Considering you're using MakeInstall on Windows, regardless of what you downloaded with gibMacOS, it will only create recovery installers as Windows doesn't have native read/write capabilities with HFS+.  In order to create a full installer, you'd need read/write access to HFS+ volumes.

-CorpNewt

**Comment by Emanuele-1998** [comment]
> Considering you're using MakeInstall on Windows, regardless of what you downloaded with gibMacOS, it will only create recovery installers as Windows doesn't have native read/write capabilities with HFS+. In order to create a full installer, you'd need read/write access to HFS+ volumes.
> 
> -CorpNewt

ok out of curiosity why then can you only install the recovery? what's the point in downloading the whole file or just the recovery if then makeinstall just puts the recovery in the usb?

at this point the complete downloaded files as recomposed to bring them to osx to then do the usb?

**Comment by Emanuele-1998** [comment]
@corpnewt ok why then can you only install the recovery? what's the point in downloading the whole file or just the recovery if then makeinstall just puts the recovery in the usb?

at this point the complete downloaded files as well as reassemble them to bring them to osx as .dmg and then do the USB?

**Comment by Emanuele-1998** [comment]
@corpnewt  ok why then can you only install the recovery? what's the point in downloading the whole file or just the recovery if then makeinstall just puts the recovery in the usb?

at this point can I compact the files downloaded from gibmacos into .dmg?

**Comment by corpnewt** [comment]
gibMacOS doesn't just work on Windows.  It also works on macOS and linux.  As such, it makes sense to let the user choose what to download for their specific situation.

The BuildmacOSInstallApp.command is macOS-only and can utilize the full install file list.

MakeInstall is Windows-only and creates only an internet recovery installer.

But gibMacOS itself is cross-platform.

-CorpNewt

**Comment by Emanuele-1998** [comment]
> gibMacOS doesn't just work on Windows. It also works on macOS and linux. As such, it makes sense to let the user choose what to download for their specific situation.
> 
> The BuildmacOSInstallApp.command is macOS-only and can utilize the full install file list.
> 
> MakeInstall is Windows-only and creates only an internet recovery installer.
> 
> But gibMacOS itself is cross-platform.
> 
> -CorpNewt

@corpnewt  thanks for explanation.

at this point if I’m in Windows  can I compact the files downloaded from gibmacos into .dmg?

**Comment by corpnewt** [comment]
Not to my knowledge - at least not with native Windows.  I've never had to try though, so you're on your own there.

-CorpNewt
