### ISSUE TITLE
dd link is dead

### ISSUE THREAD

**Issue by Poliwrath** [corpnewt/gibMacOS#41]
https://www.chrysocome.net/dd
http://www.chrysocome.net/downloads/ddrelease64.exe

```

Site Not Found

Well, this is awkward. The site you're looking for is not here.

Is this your site? Get more info or contact support.
DreamHost
```

**Comment by corpnewt** [comment]
Interesting - I just tested now, and it works fine here (both via MakeInstall and in my browser):

![image](https://user-images.githubusercontent.com/12772521/69193143-b6e0ce80-0aeb-11ea-88d1-2cdd403e40ab.png)

![image](https://user-images.githubusercontent.com/12772521/69193159-bfd1a000-0aeb-11ea-9ee4-b0008ce5b2f5.png)


-CorpNewt

**Comment by shafarizkyf** [comment]
me too, cant download via browser or .bat. Fixed by using proxy or vpn
