### ISSUE TITLE
No connection in recovery mode

### ISSUE THREAD

**Issue by Emanuele-1998** [corpnewt/gibMacOS#42]
I'm trying to download the system from macos through recovery, boot the computer with connected ethernet and there is also the kext but why doesn't it work?. I have intelMausi 

https://imgur.com/a/GWiR8RB

**Comment by corpnewt** [comment]
That's an issue with Clover r5093+

[This commit](https://github.com/corpnewt/gibMacOS/commit/7d36bd2b3b173d0b1e2417793a8bf7c8b04ff612) allows you to specify which Clover version to attempt to install.

-CorpNewt

**Comment by Emanuele-1998** [comment]
Sorry I don’t understand the resolution

**Comment by corpnewt** [comment]
When running MakeInstall - include `r5092` in the command args.

For instance - if your target disk is number 4, you would type `4 r5092`

-CorpNewt

**Comment by Emanuele-1998** [comment]
I try with high Sierra and 5092 but doesn’t work
