### ISSUE TITLE
There is a strange problem

### ISSUE THREAD

**Issue by sighzh** [corpnewt/gibMacOS#45]
Why does it always attention me "cannot install or locate 7zip"?

**Comment by corpnewt** [comment]
Looks like the script is trying to perform some operation on a "closed file" - which is when a file handle is accessed after it's done interacting with things.  I'll look at the code to verify things on my end - but I haven't seen anyone else experience this error that I can recall.

-CorpNewt

**Comment by sighzh** [comment]
I cannot avoid it happened. I tried to download 7-zip manually,  add environment path for 7-zip, and delete the file which is downloaded from the script. But it didn't resolved it. Finally, I used Etcher to make startup disk, and replaced the clover folder. Fortunately, I succeed and felt a sense of relief. Thanks for your help.

**Comment by sighzh** [comment]
> Looks like the script is trying to perform some operation on a "closed file" - which is when a file handle is accessed after it's done interacting with things. I'll look at the code to verify things on my end - but I haven't seen anyone else experience this error that I can recall.
> 
> -CorpNewt

I cannot avoid it happened. I tried to download 7-zip manually, add environment path for 7-zip, and delete the file which is downloaded from the script. But it didn't resolve it. Finally, I used Etcher to make startup disk, and replaced the clover folder. Fortunately, I succeed and felt a sense of relief. Thanks for your help.

**Comment by corpnewt** [comment]
I'll leave this issue open for awhile to see if others have similar troubles - but I've not experienced this myself, nor heard of anyone else who's had it happen.

I'm glad you were able to resolve it with Etcher though.

-CorpNewt
