### ISSUE TITLE
No internet connection in recovery 

### ISSUE THREAD

**Issue by Emanuele-1998** [corpnewt/gibMacOS#46]
I try install with high Sierra and 5092 but doesn’t work. I start the installer macOS with Ethernet but doesn’t download

I make the usb with makeinstall and I insert in the string (number of usb and r5092)

**Comment by Hackintosh-Italia** [comment]
Hi, Sorry for the wrong section but I wanted to inform that in clover bootloader 5102 fix the ethernet in recovery.

My thread 

https://github.com/CloverHackyColor/CloverBootloader/issues/49

please unlock my account Emanuele-1998 i am just trying to help.
