### ISSUE TITLE
Error writing file: 5 Access is denied.

### ISSUE THREAD

**Issue by Dr-DaNk** [corpnewt/gibMacOS#48]
I cannot figure out how to solve this damn problem! No matter what I do, I always get this error when it copies the image to the drive. I'm on an admin account. I run MakeInstall.bat as administrator, I've even given BATCH admin permissions. If anyone could help me out, that would be great.

**Comment by Dr-DaNk** [comment]
Closed

**Comment by jfdami** [comment]
I found the answer for this today. Your windows defender setting needs to change for unblocking this. Follow the instructions on [this page] (https://answers.microsoft.com/en-us/protect/forum/protect_defender-protect_scanning-windows_10/windows-defender-is-blocking-too-much-saying-it/83a1d803-c687-4ddc-800b-5bb53c6151d1)
