### ISSUE TITLE
Windows 1903

### ISSUE THREAD

**Issue by zoomos** [corpnewt/gibMacOS#5]
I've tried to run the script with Windows 1903 and it just goes to EOF without doing anything.

Removed @echo off and I attached a screenshot.
![{31885915-9FC3-4E5D-90DE-176691FFD225} png](https://user-images.githubusercontent.com/2121164/58388016-8b15dd80-7fcd-11e9-83a6-a5eaa20f014d.jpg)

**Comment by corpnewt** [comment]
What's the output of `python -V` in cmd?

**Comment by zoomos** [comment]
I decided to do a fresh install of 1903 instead of a upgrade and everything is working.

When I would type python, it would load up the App Store to install a linux package (ubuntu etc) but would fail. now it works :)
