### ISSUE TITLE
Linux and WiFi support

### ISSUE THREAD

**Issue by Emanuele-1998** [corpnewt/gibMacOS#50]
Hi, gibMacOS is compatible with linux? 

And work with the WiFi with clover 5092?

**Comment by corpnewt** [comment]
> Hi, gibMacOS is compatible with linux?

gibMacOS itself is, MakeInstall is not.

> And work with the WiFi with clover 5092?

This isn't a place to ask questions about whether or not your WiFi will work with a particular version of Clover - this is for issues with the gibMacOS script suite.

-CorpNewt

**Comment by Emanuele-1998** [comment]
> > Hi, gibMacOS is compatible with linux?
> 
> gibMacOS itself is, MakeInstall is not.
> 
> > And work with the WiFi with clover 5092?
> 
> This isn't a place to ask questions about whether or not your WiFi will work with a particular version of Clover - this is for issues with the gibMacOS script suite.
> 
> -CorpNewt

I thought the WiFi didn't work in recovery but only ethernet.

for macos instead I use the buildmacinstallapp after downloading the recovery from mac? how exactly does the buildinstallapp work?

**Comment by corpnewt** [comment]
> I thought the WiFi didn't work in recovery but only ethernet.

Whether it does or not - this is not the place to inquire.

> for macos instead I use the buildmacinstallapp after downloading the recovery from mac? how exactly does the buildinstallapp work?

You can look at the source code to find out what it's doing.

-CorpNewt

**Comment by sandhoners123** [comment]
Also Linux support is coming as a PR you know @Emanuele-1998

**Comment by Emanuele-1998** [comment]
> Also Linux support is coming as a PR you know @Emanuele-1998

@sandhoners123 i don’t understand

**Comment by sandhoners123** [comment]
@Emanuele-1998 see the open Prs. MakeInstall is getting Linux support soon
