### ISSUE TITLE
MakeInstall.bat does not open

### ISSUE THREAD

**Issue by kbedrich** [corpnewt/gibMacOS#58]
Got python installed, tried from their site and from the windows store, too.

The python file of MakeInstall does work, however, in that script I'm having issues with diskpart.
Here's what I'm getting once I select the drive: "diskpart exited with non-zero status (1). aborting"
I updated to the latest version of windows (I tried it on 1903 and 1909), with 2 different USB drives, and I'm getting the same error every time.

I'm trying to get MakeInstall.bat to open to get around the issue with the python file, however it won't open. It comes up with a command prompt window but just for a split second, it closes after that. I ran it as an admin, still didn't work.

**Comment by corpnewt** [comment]
Can you open a cmd prompt as admin, then cd into the gibMacOS directory and run `MakeInstall.bat` manually from there?  That will keep the window open so hopefully we can catch any errors.

-CorpNewt

**Comment by kbedrich** [comment]
Did that, it opened. Popped up with this:
Verifying OS name...
 - Name = NT
Verifying OS version...
 - Version = 18362

18362 >= 9600, continuing...
Traceback (most recent call last):
  File "C:\Users\kyle\Desktop\gibMacOS-master\MakeInstall.py", line 717, in <module>
    w = WinUSB()
  File "C:\Users\kyle\Desktop\gibMacOS-master\MakeInstall.py", line 12, in __init__
    self.d = diskwin.Disk()
  File "C:\Users\kyle\Desktop\gibMacOS-master\Scripts\diskwin.py", line 8, in __init__
    self.r = run.Run()
AttributeError: module 'run' has no attribute 'Run'

I'm running Python 3.8, too.

**Comment by corpnewt** [comment]
See [this issue](https://github.com/corpnewt/gibMacOS/issues/21).  Are you running Anaconda3's interpreter?  This has its own Run module - and conflicts with mine.  If so, removing that should fix the issue.

-CorpNewt

**Comment by kbedrich** [comment]
Uninstalled that and got it working. Thanks so much!
