### ISSUE TITLE
Can't download 10.14 Mojave

### ISSUE THREAD

**Issue by YanYangC** [corpnewt/gibMacOS#59]
I successfully used gibMacOS to download 10.15, however when I attempt to download 10.14 it downloads the subcatalogue, attempts to download 10.14 for around 0.2 of a second, then instantly fails

**Comment by YanYangC** [comment]
![image](https://user-images.githubusercontent.com/59201727/71422666-d1bed980-267b-11ea-9c41-0e43c979c8fd.png)

**Comment by YanYangC** [comment]
I was able to download the package I wanted by manually finding the url within the subcatalogue however.

**Comment by corpnewt** [comment]
Looks like the name ended up with an erroneous space at the end - fixed in [this commit](https://github.com/corpnewt/gibMacOS/commit/8dc2a1c78a81491ddbc44f72f192f884dd99893d).

-CorpNewt
