### ISSUE TITLE
No disks detected

### ISSUE THREAD

**Issue by Bosskee** [corpnewt/gibMacOS#6]
Hello!

Trying to use the MakeInstall.bat but I've encountered what I think is a problem.

When I open the batch file, the UI looks like this:
https://i.gyazo.com/ea357d90c351099386faa4646fe8d6db.png

No disks appear and I can't figure out why. Any idea what might be causing this?

**Comment by corpnewt** [comment]
If you run the following in cmd and look at the output
```
wmic logicaldisk get deviceid,filesystem,volumename,size,drivetype /format:csv
```
You should get something like this:
```
CORP-WIN10,C:,3,NTFS,499513290752,Win10
CORP-WIN10,E:,3,NTFS,749859762176,Games
CORP-WIN10,I:,3,HFSJ,499248103424,Bluenose
CORP-WIN10,K:,3,HFSJ,249484636160,Lifeboat
CORP-WIN10,Y:,4,HFSJ,4000443056128,Mammoth
CORP-WIN10,Z:,4,HFSJ,4000443056128,Goliath
```

The numbers after the drive letter show what type the drive is (0 = Unknown, 1 = No Root Dir, 2 = Removable, 3 = Local, 4 = Network, 5 = Disc, 6 = RAM disk).  In my above snipped, you can see I have 4 local disks, and 2 network disks attached - but no unknown or removable.  Currently the script only looks for types 0 and 2 (Unknown and Removable).  If your disks are not shown as such, they won't show up in the script.

```py
    def get_disks_of_type(self, disk_list, disk_type=(0,2)):
        disks = {}
        for disk in disk_list:
            if disk_list[disk].get("type",0) in disk_type:
                disks[disk] = disk_list[disk]
        return disks
```

**Comment by Bosskee** [comment]
Thank you for a detailed response.

I managed to fix the issue, which as it turns out had nothing to do with your script. WMIC wasn't pointed towards correctly in the PATH.

**Comment by Sweasfour** [comment]
How do i change the path ? bcz i have the same problem

**Comment by NorthernFlow** [comment]
I made sure of everything described in this post and still not showing any disks. PATH of WMIC is correct.
I am using Windows 11 and WMIC is just not working on this system. It says ERROR, Description = invalid namespace. Tho, I confirmed that my usb is removable by WMIC on another PC with Windows 7. I tried to run gibMacOS on windows 7 but it says it needs windows ver.9600 minimum. Gosh...

I guess it's helpless...

**Comment by wilkergrcv** [comment]
If you are using an external hard drive instead of a flash drive, change this line in the MakeInstall.py file.

By default it will be like this:

def get_disks_of_type(self, disk_list, disk_type=(0,2)):

with this configuration makeinstall will only show removable and unknown devices

now just change that same line with a 3 looking like this

def get_disks_of_type(self, disk_list, disk_type=(0,2,3)):

save the file and run MakeInstall.bat again and be happy.
