### ISSUE TITLE
DiskPart exited with non-zero status (1).  Aborting.

### ISSUE THREAD

**Issue by firefox15** [corpnewt/gibMacOS#62]
I've read through all the issues (closed and open) in GitHub and tried all the suggestions that I could, but unfortunately, I'm not able to get this to work.  I'm running Windows 10 x64 1909 with all available updates installed.  I've tried three different USB sticks from different manufacturers and different USB ports.  I've tried running it as admin and letting the script self-elevate, but they all fail with the same error:

`DiskPart exited with non-zero status (1).  Aborting.`

DiskPart codes look like it is simply saying it is a "fatal error."  However, I looked at the Python script, and it appears that it is trying to run the following block:

```
"select disk {}".format(disk.get("index",-1)),
"clean",
"convert mbr",
"create partition primary size=200",
"format quick fs=fat32 label='CLOVER'",
"active",
"create partition primary id=AB" # AF = HFS, AB = Recovery
```

Running these commands (without the comments and commas and such, obviously, and substituting the proper disk in the select statement) in diskpart itself works just fine and creates a drive that looks like the following, but the script seems to be having an issue with it, and unfortunately, I'm not good enough with Python to troubleshoot it further.  Any ideas?  Thanks for all the hard work on this!

![image](https://user-images.githubusercontent.com/16748083/71593283-71a7b780-2b01-11ea-94fd-47abb26a936c.png)

**Comment by firefox15** [comment]
So I busted out ProcMon to see what is going on, and there appears to be something wrong with the way the script is enumerating the path variables when trying to locate `diskpart`.  If an environmental variable is used in a path like this, the script does not expand it properly:

![image](https://user-images.githubusercontent.com/16748083/71597372-d74f7000-2b10-11ea-8705-525a01df3d67.png)

Instead of expanding it, it just pre-pends the script path to it (not sure why), and therefore it will never find `diskpart`.

![image](https://user-images.githubusercontent.com/16748083/71597461-3614e980-2b11-11ea-8570-525556c9d301.png)

I was able to work around this by hardcoding an environmental variable to `C:\Windows\System32\` where `diskpart` is located, but I'm guessing it would be best if the script where modified to account for this in the future as this is the default configuration for Windows 10.

Unfortunately, I'm now having the following issue (No partitions located on disk!), and I am not sure if the issue is related or not.  Any assistance would be appreciated. #13

**Comment by firefox15** [comment]
Regarding the latest issue of "No partitions located on disk!", it appears that Clover needs to have a drive letter assigned to the Clover partition, or the script will fail because the following two WMI commands will not find the partition without it:

```
wmic path Win32_LogicalDiskToPartition get antecedent,dependent
wmic logicaldisk get deviceid,filesystem,volumename,size,drivetype /format:csv
```
I was able to bypass this by assigning a drive letter before the Clover step.  I believe modifying the `diskpart` commands to assign a drive letter would likely fix the issue and would resolve #13, #23, #29, and #51 while changing the path logic should fix #25, #37, and #57.

**Comment by corpnewt** [comment]
I appreciate you taking the time to look through this.  I'll see if there's anything I can do to improve the pathing logic - and assigning a drive letter could likely be done in the script passed to `diskpart` when formatting.

-CorpNewt

**Comment by firefox15** [comment]
Fantastic, that looks to have fixed both issues.  Thanks!  Now I'm off to hopefully figure out how to use this to install macOS in VMware Workstation.  I'll close this issue since both of my problems were fixed.  I appreciate the quick response!

**Comment by ToPoorToDream** [comment]
Has it been updated already or what?
