### ISSUE TITLE
gibMacOS.bat Download stuck on 100%

### ISSUE THREAD

**Issue by marmik18** [corpnewt/gibMacOS#65]
####################
Downloading File 11 of 11
####################
AppleDiagnostics.dmg --> Succeeded
BaseSystem.dmg --> Succeeded
InstallAssistantAuto.pkg --> Succeeded
MajorOSInfo.pkg --> Succeeded
RecoveryHDMetaDmg.pkg --> Succeeded
InstallInfo.plist --> Succeeded
OSInstall.mpkg --> Succeeded
BaseSystem.chunklist --> Succeeded
AppleDiagnostics.chunklist --> Succeeded
InstallESDDmg.chunklist --> Succeeded

Downloading InstallESDDmg.pkg for 041-91758 - 10.13.6 macOS High Sierra...

Downloaded 4.72 GB of 4.72 GB (100.0%)
------------------------------------------------------------------------------------------

This is what I see on the cmd. The download is not Successful. Please help. Thank you.

**Comment by NoDreaminger** [comment]
If you are windows that trying to refresh by pressing F5.
