### ISSUE TITLE
NameError: name 'downloader' is not defined

### ISSUE THREAD

**Issue by fralyx** [corpnewt/gibMacOS#69]
![gib](https://user-images.githubusercontent.com/8995187/72673236-116dbb00-3a9a-11ea-8e05-0d585695f04e.png)

**Comment by corpnewt** [comment]
Did you download the whole project?  If so - are you launching it via the .bat scripts included?

**Comment by fralyx** [comment]
Yes, I tried to download from both zip option and git clone, same result

**Comment by corpnewt** [comment]
> If so - are you launching it via the .bat scripts included?

**Comment by fralyx** [comment]
> > If so - are you launching it via the .bat scripts included?

Yep

**Comment by fralyx** [comment]
I'm trying to follow the vanilla osx guide on https://vanilla.amd-osx.com/

**Comment by fralyx** [comment]
I later found out that it's just a problem with directories that has spaces. Moving to a directory with no space solves it
