### ISSUE TITLE
Installed Python...gbiMacOS.bat does nothing

### ISSUE THREAD

**Issue by tl5k5** [corpnewt/gibMacOS#70]
After downloading and extracting the embedded python 3.8.1 and putting in the proper Windows environment path, the gibMacOS.bat will bring up an cmd shell, then quickly disappear.
It seems to just crash out.

**Comment by corpnewt** [comment]
Open a cmd window, cd into the gibMacOS directory, and type `gibMacOS.bat`, then press enter and show me what it says.

**Comment by tl5k5** [comment]
After turning off UAC (w/ reboot) and then running the gibMacOS.bat directly in a CMD shell, it is now working.  I don't know if it was UAC or just running it directly in a CMD shell.

**Comment by corpnewt** [comment]
So it all works after the reboot?

**Comment by tl5k5** [comment]
When you turn off UAC, a reboot is required for the new setting to work.  Yes, after that reboot your script worked.

**Comment by corpnewt** [comment]
Shouldn't require UAC prompting at all for gibMacOS.bat - as that doesn't need any elevated perms.

**Comment by tl5k5** [comment]
ok...so maybe it was the fact that I ran it from a path instead of double clicking the .bat file.

**Comment by corpnewt** [comment]
Alright - glad it's working now.  I'll go ahead and close this issue.

-CorpNewt
