### ISSUE TITLE
Linux MakeInstall.py error

### ISSUE THREAD

**Issue by tl5k5** [corpnewt/gibMacOS#72]
Had trouble on windows so switched over to linux.
When I run MakeInstall.py I get:
`>$ ./MakeInstall.py
from: can't read /var/mail/Scripts
' @ error/constitute.c/WriteImage/1037.
./MakeInstall.py: line 3: $'\r': command not found
./MakeInstall.py: line 4: class: command not found
./MakeInstall.py: line 5: $'\r': command not found
./MakeInstall.py: line 6: syntax error near unexpected token `('
'/MakeInstall.py: line 6: `    def __init__(self):`

**Comment by corpnewt** [comment]
MakeInstall only works on Windows.

**Comment by tl5k5** [comment]
ok
