### ISSUE TITLE
makeinstall.py exits with error when running diskpart script

### ISSUE THREAD

**Issue by haplopeart** [corpnewt/gibMacOS#75]
The Script through 3 version now has failed on my machine.  I've had to fix it the same way in each version.  I thought I'd contribute the fix which is a couple additional lines, and one edited line.

Revised diskpart script:
`"select disk {}".format(disk.get("index",-1)),
                "clean",
                "convert mbr",
                "create partition primary size=200",
                "format quick fs=fat32 label='BOOT'",
                "active",
                "create partition primary", # setting the ID Here caused the machine to hang and the script to fail after several minutes, saying the device was not ready and to issue a rescan command
                "rescan",  #added rescan command
                "select part 1",
                "set id=AB OVERRIDE", # AF = HFS, AB = Recovery, moved id setting to here
                "sel vol {}".format(disk.get("index",-1)), # now have to tell it where to select the volume before assignment
                "assign"`

**Comment by pedrorambo** [comment]
A similar error is happening to me. It occurs when creating the second partition, but the script from @haplopeart doesn't worked for me. Using the Windows _Disk Management_, it doesn't allow me to create a second partition (it doesnt show the _New Simple Volume_ option on the unallocated space). I tested it on 2 USBs, and when using _GParted_ on Linux, it worked.

### Running with MBR:

**MakeInstall error message:**
 `DiskPart exited with non-zero status (-2147024809).  Aborting.
`

**Diskpart error message:**
```
No usable free extent could be found. It may be that there is insufficient
free space to create a partition at the specified size and offset. Specify
different size and offset values or don't specify either to create the
maximum sized partition. It may be that the disk is partitioned using the MBR disk
partitioning format and the disk contains either 4 primary partitions, (no
more partitions may be created), or 3 primary partitions and one extended
partition, (only logical drives may be created).
```

### Running with GPT:

**MakeInstall error message:**
`DiskPart exited with non-zero status (-2147211941).  Aborting.
`

**Diskpart error message:**
```
Virtual Disk Service error:
The operation is not supported on a non-empty removable disk.
```


The program runs "clean" command, so there isn't any user-defined partitions, or insufficient free space.

**Running manually the diskpart commands:**
```
select disk 4
clean
convert mbr
create partition primary size=200
format quick fs=fat32 label='BOOT'
active
create partition primary (and with id=AB - same error)
Virtual Disk Service error:
The operation is not supported on a non-empty removable disk.
```


OS: Windows 10 Enterprise 2016 LTSB 64-bit
USBs tested (2): Kingston Data Traveler 3.0 16GB and a generic USB 2.0 8GB

**Comment by haplopeart** [comment]
Ignore my fix...its NG!
After days of trying to get a system running I realize the fix I created doesn't create a working key.  Causes the system to never find the root device "Still waiting for root device" and Prohibited sign error.  It seemed the system I was trying to create the key on just doesn't like to run the diskpart.  On a different windows system it all worked out first try.
