### ISSUE TITLE
Currently running Windows-7-6.1.7601-SP1, this script requires version 9600 or newer.

### ISSUE THREAD

**Issue by gitHubForLz** [corpnewt/gibMacOS#76]
see title

**Comment by corpnewt** [comment]
The script doesn't work on Windows 7 - hence the error message.

-CorpNewt

**Comment by hansoljin** [comment]
Here's the weird thing. winver says I'm on Windows 10 (build 18362) which is twice as high as 9600. Command prompt says I'm on Windows-8-6.2.9200.

Is something wrong with my system?
