### ISSUE TITLE
DiskPart has encountered an error:

### ISSUE THREAD

**Issue by azalmover2019** [corpnewt/gibMacOS#88]
Formatted usb drive as FAT32 via Disk Management tool and went through the install.bat file but I keep getting this message: 

DiskPart exited with a non-zero status (2147942401). Am I doing something wrong?

Microsoft DiskPart version 10.0.18362.1

**Comment by azalmover2019** [comment]
Seems like a corrupted USB. The tool works as expected.

**Comment by kasusa** [comment]
well I have the same problem.
```
DiskPart exited with non-zero status (2147942401).  Aborting.        
```
