### ISSUE TITLE
Updating the MBR with boot0af... - An error occurred updating the MBR: 1

### ISSUE THREAD

**Issue by Linuxerowo** [corpnewt/gibMacOS#9]
I came across this error while I was creating the USB. By the way I was using this guide (https://internet-install.gitbook.io/macos-internet-install/preparing-your-installer.../preparing-your-installer-media...) Here it is: "Updating the MBR with boot0af... - An error occurred updating the MBR: 1" Help is appreciated!!! Thanks!

**Comment by corpnewt** [comment]
Likely either the windows configuration or the USB - try another machine, updating Windows, or trying another USB.  Most of the issues users have with MakeInstall.py can be resolved by changing USB drives and verifying Windows is installed and configured correctly.

-CorpNewt
