### ISSUE TITLE
does open core 0.5.7 support legacy bios

### ISSUE THREAD

**Issue by karungupta762** [corpnewt/gibMacOS#97]
does open core 0.5.7 support legacy bios as i am not able to boot open core using this version

there is a solution to load any version of clover by tyonig the serial number of version like 5092 or 5098 or 5110 or 5114

but for open core , it is default fixed to 0.5.7 can I change the version to any other one

please suggest me a way so that i can boot with any other version of open core that supports legacy bios

**Comment by corpnewt** [comment]
Closed as duplicate of issue 94
